import type { Show } from "./types.ts";

/**
 * The schedule, as shapes rather than as lists.
 *
 * Each show owns a CLOCK: the order of an hour, with music slots naming
 * a rotation rather than a record. Two things follow from that and both
 * are the point of the template. A show sounds the way it does because
 * of the shape, not because somebody picked twelve nice songs — swap
 * `library` for `a` in three slots and the hour is a different station.
 * And the hour lands because exactly one slot is `flex`: the host's
 * back-announce, which is however long the hour needs.
 *
 * The automated show has no flex slot, and that single missing line is
 * the whole argument on the front page.
 *
 * The speech lengths below are not arbitrary. Each clock is built so its
 * fixed content leaves the back-announce somewhere near the middle of
 * the twenty-second to four-minute range it is allowed — which is what
 * gives it room to absorb the difference between a three-minute record
 * and a five-minute one without ever running out. An hour whose
 * back-announce is pinned at either end is an hour that misses.
 */
export const shows: Show[] = [
  {
    id: "first-light",
    name: "First Light",
    host: "R.O.",
    hosts: "Robin Ostergaard",
    mode: "hosted",
    blurb:
      "Six until nine. Tide, bar conditions, the school run, and enough records between them that nobody has to talk before they are ready.",
    clock: [
      { k: "ident", s: 12, title: "Top-of-hour identification", fixed: true },
      { k: "music", cat: "a" },
      { k: "music", cat: "b" },
      { k: "link", s: 60, title: "Time, tide and the bar" },
      { k: "music", cat: "local" },
      { k: "music", cat: "a" },
      { k: "spot" },
      { k: "music", cat: "library" },
      { k: "news", s: 240, title: "Bay and bar report" },
      { k: "music", cat: "b" },
      { k: "music", cat: "a" },
      { k: "link", s: 100, title: "The morning read" },
      { k: "music", cat: "library" },
      { k: "music", cat: "b" },
      { k: "spot" },
      { k: "music", cat: "a" },
      { k: "ident", s: 8, title: "Sweeper" },
      { k: "promo", s: 60, title: "On Wren today" },
      { k: "music", cat: "library" },
      { k: "link", s: 60, title: "Back-announce and what is coming", flex: true },
      { k: "music", cat: "b" },
    ],
  },
  {
    id: "long-table",
    name: "The Long Table",
    host: "P.R.",
    hosts: "Priya Raman",
    mode: "hosted",
    blurb:
      "Nine until twelve. One long conversation an hour with somebody who does a thing here, and records either side of it.",
    clock: [
      { k: "ident", s: 12, title: "Top-of-hour identification", fixed: true },
      { k: "music", cat: "a" },
      { k: "music", cat: "b" },
      { k: "link", s: 65, title: "What is on the table" },
      { k: "music", cat: "local" },
      { k: "spot" },
      { k: "music", cat: "library" },
      { k: "music", cat: "a" },
      { k: "news", s: 300, title: "The conversation" },
      { k: "music", cat: "b" },
      { k: "music", cat: "library" },
      { k: "spot" },
      { k: "music", cat: "a" },
      { k: "music", cat: "library" },
      { k: "ident", s: 8, title: "Sweeper" },
      { k: "music", cat: "b" },
      { k: "link", s: 60, title: "Back-announce", flex: true },
      { k: "music", cat: "a" },
      { k: "music", cat: "library" },
    ],
  },
  {
    id: "bay-notices",
    name: "Bay Notices",
    host: "D.M.",
    hosts: "Del Marchetti",
    mode: "hosted",
    blurb:
      "Midday. The noticeboard hour — harbour board, school district, the roster, the thanks. Mostly speech, and the only hour of the day anybody records to listen back to.",
    clock: [
      { k: "ident", s: 12, title: "Top-of-hour identification", fixed: true },
      { k: "news", s: 240, title: "Tide, bar and small craft" },
      { k: "music", cat: "a" },
      { k: "news", s: 195, title: "School district notices" },
      { k: "music", cat: "local" },
      { k: "spot" },
      { k: "news", s: 260, title: "Council digest" },
      { k: "music", cat: "b" },
      { k: "link", s: 55, title: "Volunteer roster" },
      { k: "news", s: 210, title: "Harbour board minutes" },
      { k: "music", cat: "library" },
      { k: "news", s: 200, title: "Emergency services and the ridge road" },
      { k: "music", cat: "a" },
      { k: "spot" },
      { k: "news", s: 260, title: "Arts, sports and the events diary" },
      { k: "music", cat: "b" },
      { k: "ident", s: 8, title: "Sweeper" },
      { k: "news", s: 165, title: "Thanks, notices and obituaries" },
      { k: "music", cat: "library" },
      { k: "link", s: 60, title: "Read-back and sign-off", flex: true },
      { k: "music", cat: "local" },
    ],
  },
  {
    id: "afternoon-drift",
    name: "Afternoon Drift",
    host: "K.A.",
    hosts: "Kit Abernathy",
    mode: "hosted",
    blurb:
      "One until four. The least eventful three hours on the station, which is a compliment — it is the hour people have on while they work.",
    clock: [
      { k: "ident", s: 12, title: "Top-of-hour identification", fixed: true },
      { k: "music", cat: "a" },
      { k: "music", cat: "library" },
      { k: "link", s: 60, title: "Back-announce" },
      { k: "music", cat: "b" },
      { k: "music", cat: "a" },
      { k: "spot" },
      { k: "music", cat: "local" },
      { k: "music", cat: "b" },
      { k: "link", s: 110, title: "Weather, the crossing and the week" },
      { k: "music", cat: "a" },
      { k: "music", cat: "library" },
      { k: "spot" },
      { k: "music", cat: "b" },
      { k: "ident", s: 8, title: "Sweeper" },
      { k: "music", cat: "a" },
      { k: "music", cat: "b" },
      { k: "promo", s: 60, title: "Tonight on Wren" },
      { k: "music", cat: "a" },
      { k: "link", s: 50, title: "Into the hour", flex: true },
      { k: "music", cat: "library" },
    ],
  },
  {
    id: "crossing",
    name: "Crossing",
    host: "N.S.",
    hosts: "Nia Sowande",
    mode: "hosted",
    blurb:
      "Four until seven. Drive time, such as it is here: two ferries, one bridge and about nine hundred cars.",
    clock: [
      { k: "ident", s: 12, title: "Top-of-hour identification", fixed: true },
      { k: "music", cat: "a" },
      { k: "music", cat: "b" },
      { k: "link", s: 85, title: "Ferry, bridge and the ridge road" },
      { k: "music", cat: "a" },
      { k: "spot" },
      { k: "music", cat: "local" },
      { k: "music", cat: "b" },
      { k: "promo", s: 60, title: "Tonight on Wren" },
      { k: "music", cat: "a" },
      { k: "music", cat: "library" },
      { k: "spot" },
      { k: "music", cat: "b" },
      { k: "link", s: 60, title: "Back-announce and the roads" },
      { k: "music", cat: "a" },
      { k: "ident", s: 8, title: "Sweeper" },
      { k: "music", cat: "library" },
      { k: "spot" },
      { k: "music", cat: "b" },
      { k: "link", s: 50, title: "Out to the hour", flex: true },
      { k: "music", cat: "a" },
      { k: "music", cat: "library" },
    ],
  },
  {
    id: "local-cuts",
    name: "Local Cuts",
    host: "F.B.",
    hosts: "Ford Baptiste",
    mode: "hosted",
    blurb:
      "Seven until eight, and nothing in it was recorded more than forty miles from the transmitter. The hour the station is proudest of, and the one its own rules cannot survive.",
    clock: [
      { k: "ident", s: 12, title: "Top-of-hour identification", fixed: true },
      { k: "music", cat: "local" },
      { k: "music", cat: "local" },
      { k: "link", s: 80, title: "Who that was, and where they play" },
      { k: "music", cat: "local" },
      { k: "music", cat: "local" },
      { k: "music", cat: "local" },
      { k: "spot" },
      { k: "music", cat: "local" },
      { k: "music", cat: "local" },
      { k: "link", s: 72, title: "The Chowder Hall bill" },
      { k: "music", cat: "local" },
      { k: "music", cat: "local" },
      { k: "music", cat: "local" },
      { k: "ident", s: 8, title: "Sweeper" },
      { k: "music", cat: "local" },
      { k: "music", cat: "local" },
      { k: "link", s: 45, title: "Back-announce", flex: true },
      { k: "music", cat: "local" },
      { k: "music", cat: "local" },
    ],
  },
  {
    id: "the-slack",
    name: "The Slack",
    host: "I.C.",
    hosts: "Ines Calder",
    mode: "hosted",
    blurb:
      "Eight until ten. Named for the half hour between tides when the water does not go anywhere. Deep in the library, quiet on the microphone.",
    clock: [
      { k: "ident", s: 12, title: "Top-of-hour identification", fixed: true },
      { k: "music", cat: "library" },
      { k: "music", cat: "b" },
      { k: "link", s: 60, title: "Back-announce" },
      { k: "music", cat: "library" },
      { k: "music", cat: "local" },
      { k: "spot" },
      { k: "music", cat: "library" },
      { k: "music", cat: "a" },
      { k: "music", cat: "library" },
      { k: "link", s: 200, title: "A note on the record" },
      { k: "music", cat: "b" },
      { k: "music", cat: "library" },
      { k: "ident", s: 8, title: "Sweeper" },
      { k: "music", cat: "a" },
      { k: "music", cat: "library" },
      { k: "link", s: 50, title: "Out", flex: true },
      { k: "music", cat: "library" },
    ],
  },
  {
    id: "automation",
    name: "Automation",
    host: "—",
    mode: "automated",
    blurb:
      "Ten until two. Nobody is in the building. The playout machine takes the next record off the wheel and plays all of it, which is the reason these four hours are the least accurate on the station.",
    clock: [
      { k: "ident", s: 12, title: "Top-of-hour identification", fixed: true },
      { k: "music", cat: "night" },
      { k: "music", cat: "library" },
      { k: "music", cat: "b" },
      { k: "music", cat: "library" },
      { k: "music", cat: "night" },
      { k: "music", cat: "b" },
      { k: "music", cat: "library" },
      { k: "music", cat: "b" },
      { k: "music", cat: "night" },
      { k: "music", cat: "library" },
      { k: "music", cat: "b" },
      { k: "music", cat: "library" },
    ],
  },
  {
    id: "passing-notes",
    name: "Passing Notes",
    host: "—",
    mode: "network",
    blurb:
      "Two until six, off the satellite. A fixed junction at either end: the feed starts when it starts and the station has to be there.",
    clock: [{ k: "network", s: 3600, title: "Network feed — Passing Notes" }],
  },
];

export const showById = new Map(shows.map((s) => [s.id, s]));
