import type { Shell } from "@/lib/ballistics";

/**
 * The catalogue. Twenty shells, which is a small stock list and a
 * deliberate one — a display company's inventory is not a shop.
 *
 * The relationships in here are real and the site depends on them:
 *
 *   • Break height runs at about 30 metres per inch of diameter. A
 *     six-inch shell breaks at 180 metres, and there is no such thing as
 *     a six-inch shell that breaks low.
 *   • Lift time climbs with height but not in proportion to it, because
 *     drag does not care about your schedule. Doubling the height costs
 *     about 55% more time, not 100%.
 *   • Burst diameter runs at about 33 metres per inch, so a twelve-inch
 *     shell fills four hundred metres of sky.
 *   • Price is where the chemistry shows. Compare the three matched
 *     pairs — 3-inch, 6-inch and 12-inch, gold against blue, same size
 *     and same effect. `scripts/check-show.mjs` asserts that the blue is
 *     dearer in every pair, because that gap is an argument the site
 *     makes in prose and prose is the thing nothing else can check.
 */
export const SHELLS: readonly Shell[] = [
  {
    id: "p2-gold",
    name: "2in Gold Peony",
    sizeInches: 2,
    altitudeM: 60,
    liftTenths: 21,
    burstM: 66,
    burnTenths: 14,
    stars: 24,
    emissions: ["gold"],
    effect: "Peony",
    costUsd: 6,
    note: "The finale shell. Nobody looks at one of these; they look at ninety of them.",
  },
  {
    id: "p2-amber",
    name: "2in Amber Peony",
    sizeInches: 2,
    altitudeM: 60,
    liftTenths: 21,
    burstM: 66,
    burnTenths: 13,
    stars: 24,
    emissions: ["amber"],
    effect: "Peony",
    costUsd: 7,
    note: "Sodium, so it is far brighter than its size suggests and it flattens anything fired beside it.",
  },
  {
    id: "p3-gold",
    name: "3in Gold Peony",
    sizeInches: 3,
    altitudeM: 90,
    liftTenths: 26,
    burstM: 100,
    burnTenths: 17,
    stars: 42,
    emissions: ["gold"],
    effect: "Peony",
    costUsd: 14,
    note: "The workhorse of the whole trade, and the cheapest thing here that reads as a proper firework.",
  },
  {
    id: "p3-red",
    name: "3in Red Peony",
    sizeInches: 3,
    altitudeM: 90,
    liftTenths: 26,
    burstM: 100,
    burnTenths: 17,
    stars: 42,
    emissions: ["red"],
    effect: "Peony",
    costUsd: 17,
    note: "Strontium. Three pounds more than the gold, for a star that puts out about half the light.",
  },
  {
    id: "p3-green",
    name: "3in Green Peony",
    sizeInches: 3,
    altitudeM: 90,
    liftTenths: 26,
    burstM: 100,
    burnTenths: 16,
    stars: 42,
    emissions: ["green"],
    effect: "Peony",
    costUsd: 18,
    note: "Barium. Reads cleanly against a black sky and disappears entirely against a lit town.",
  },
  {
    id: "p3-blue",
    name: "3in Blue Peony",
    sizeInches: 3,
    altitudeM: 90,
    liftTenths: 26,
    burstM: 100,
    burnTenths: 15,
    stars: 42,
    emissions: ["blue"],
    effect: "Peony",
    costUsd: 24,
    note: "The matched pair to the gold, at not quite twice the price, for a quarter of the light.",
  },
  {
    id: "p3-silver",
    name: "3in Silver Peony",
    sizeInches: 3,
    altitudeM: 90,
    liftTenths: 26,
    burstM: 100,
    burnTenths: 15,
    stars: 46,
    emissions: ["silver"],
    effect: "Peony",
    costUsd: 16,
    note: "Titanium, and it crackles. The cheapest way to make a small shell sound like a large one.",
  },
  {
    id: "c4-amber",
    name: "4in Amber Chrysanthemum",
    sizeInches: 4,
    altitudeM: 120,
    liftTenths: 31,
    burstM: 132,
    burnTenths: 22,
    stars: 96,
    emissions: ["amber"],
    effect: "Chrysanthemum",
    costUsd: 27,
    note: "Trailing stars rather than points — the difference between a chrysanthemum and a peony is the tail.",
  },
  {
    id: "c4-silver",
    name: "4in Silver Chrysanthemum",
    sizeInches: 4,
    altitudeM: 120,
    liftTenths: 31,
    burstM: 132,
    burnTenths: 21,
    stars: 96,
    emissions: ["silver"],
    effect: "Chrysanthemum",
    costUsd: 31,
    note: "Reads white against everything, which is why it opens more shows than any other shell in this list.",
  },
  {
    id: "x4-purple",
    name: "4in Purple Crossette",
    sizeInches: 4,
    altitudeM: 120,
    liftTenths: 31,
    burstM: 145,
    burnTenths: 19,
    // A hundred and twenty-eight BURNING points, from thirty-two stars
    // that each split. Counting the thirty-two would be counting what
    // is loaded rather than what is seen, and it made purple look like
    // the most expensive light in the trade by a factor of four —
    // an artefact of the count, not a fact about copper.
    stars: 128,
    emissions: ["purple"],
    effect: "Crossette",
    costUsd: 44,
    note: "Each star splits into four. Thirty-two stars become a hundred and twenty-eight, and every one of them is copper.",
  },
  {
    id: "p5-orange",
    name: "5in Orange Peony",
    sizeInches: 5,
    altitudeM: 150,
    liftTenths: 35,
    burstM: 165,
    burnTenths: 20,
    stars: 128,
    emissions: ["orange"],
    effect: "Peony",
    costUsd: 48,
    note: "Calcium. Ordered twice a year, both times by clients who saw it in a catalogue and not in the air.",
  },
  {
    id: "c6-gold",
    name: "6in Gold Chrysanthemum",
    sizeInches: 6,
    altitudeM: 180,
    liftTenths: 40,
    burstM: 200,
    burnTenths: 26,
    stars: 180,
    emissions: ["gold"],
    effect: "Chrysanthemum",
    costUsd: 62,
    note: "If a show has one shell in it more than any other, it is almost always this one.",
  },
  {
    id: "c6-blue",
    name: "6in Blue Chrysanthemum",
    sizeInches: 6,
    altitudeM: 180,
    liftTenths: 40,
    burstM: 200,
    burnTenths: 24,
    stars: 180,
    emissions: ["blue"],
    effect: "Chrysanthemum",
    costUsd: 118,
    note: "The matched pair to the gold, at very nearly double. This one shell is most of why Blue Hour cost what it did.",
  },
  {
    id: "w6-gold",
    name: "6in Gold Willow",
    sizeInches: 6,
    altitudeM: 180,
    liftTenths: 40,
    burstM: 210,
    burnTenths: 42,
    stars: 96,
    emissions: ["gold"],
    effect: "Willow",
    costUsd: 71,
    note: "Charcoal stars heavy enough to fall while they burn. Four and a half seconds of light from one break.",
  },
  {
    id: "r6-green",
    name: "6in Green Ring",
    sizeInches: 6,
    altitudeM: 180,
    liftTenths: 40,
    burstM: 195,
    burnTenths: 18,
    stars: 60,
    emissions: ["green"],
    effect: "Ring",
    costUsd: 79,
    note: "Stars laid in a plane rather than a sphere, so it only reads as a ring from one direction. Aimed at the crowd, not the sky.",
  },
  {
    id: "c8-silver",
    name: "8in Silver Chrysanthemum",
    sizeInches: 8,
    altitudeM: 240,
    liftTenths: 48,
    burstM: 264,
    burnTenths: 30,
    stars: 320,
    emissions: ["silver"],
    effect: "Chrysanthemum",
    costUsd: 155,
    note: "Nearly five seconds in the air before it does anything. Fire it late and it lands in the middle of the next thought.",
  },
  {
    id: "d10-double",
    name: "10in Double-Petal, blue core",
    sizeInches: 10,
    altitudeM: 300,
    liftTenths: 56,
    burstM: 330,
    burnTenths: 28,
    stars: 460,
    emissions: ["blue", "red"],
    effect: "Double-petal",
    costUsd: 340,
    note: "A blue sphere inside a red one. The blue survives because the red is not there to compete with it — it is behind it.",
  },
  {
    id: "c12-gold",
    name: "12in Gold Chrysanthemum",
    sizeInches: 12,
    altitudeM: 360,
    liftTenths: 63,
    burstM: 400,
    burnTenths: 34,
    stars: 720,
    emissions: ["gold"],
    effect: "Chrysanthemum",
    costUsd: 430,
    note: "Four hundred metres across. Six and three-tenths seconds in the air, which is longer than most people can hold a breath comfortably.",
  },
  {
    id: "c12-blue",
    name: "12in Blue Chrysanthemum",
    sizeInches: 12,
    altitudeM: 360,
    liftTenths: 63,
    burstM: 400,
    burnTenths: 30,
    stars: 720,
    emissions: ["blue"],
    effect: "Chrysanthemum",
    costUsd: 860,
    note: "The most expensive single object this company owns, and from the ground it is dimmer than the gold that costs half as much.",
  },
  {
    id: "w12-gold",
    name: "12in Gold Willow",
    sizeInches: 12,
    altitudeM: 360,
    liftTenths: 63,
    burstM: 420,
    burnTenths: 55,
    stars: 400,
    emissions: ["gold"],
    effect: "Willow",
    costUsd: 455,
    note: "Five and a half seconds of falling light. It is the only shell here that is still burning when the next one breaks above it.",
  },
];

/**
 * The matched pairs the price argument rests on: same diameter, same
 * effect, one gold and one blue. Named here rather than found by a
 * search so that the assertion in `check-show.mjs` is checking the
 * pairs the PROSE is about, not whichever pairs happen to exist.
 */
export const PRICE_PAIRS: readonly { gold: string; blue: string }[] = [
  { gold: "p3-gold", blue: "p3-blue" },
  { gold: "c6-gold", blue: "c6-blue" },
  { gold: "c12-gold", blue: "c12-blue" },
];
