import type { Session } from "./types";

/**
 * The whole conference, as data.
 *
 * Tuned rather than sprinkled, per CONVENTIONS §7b. Every state the
 * wallchart can draw exists exactly once or twice, deliberately:
 *
 *   - one plenary opening and one plenary closing, drawn full width
 *   - four sessions live at 11:20 on day two, which is where the clock
 *     is pinned, so the now-marker and the live treatment are visible
 *   - one sold-out workshop and one workshop with places left, so both
 *     halves of the capacity design are reachable
 *   - one cancelled session, kept on the grid struck through
 *   - one empty room column (Yard, day one, 11:55) so the "nothing
 *     here" state is real rather than theoretical
 *   - one bad collision at 14:35 on day two, where three strong talks
 *     run against each other AND against the tail of a ninety-minute
 *     workshop that started an hour earlier. The fourth is the one that
 *     matters: it is not in the 14:35 row, so a list-shaped schedule
 *     could never show it as a conflict. Only drawing time to scale
 *     makes it visible, which is this template's whole argument
 *   - one title long enough to test wrapping at every column width
 *   - a shorter final day, so the grid is not the same rectangle thrice
 *
 * `scripts/check-schedule.mjs` asserts all of it, plus the properties
 * that are easy to break by hand: no session outside its day's opening
 * hours, no room double-booked, no speaker in two places at once.
 */
export const sessions: Session[] = [
  // ── Day one — What breaks ──────────────────────────────────────────
  {
    id: "d1-01",
    slug: "doors-day-one",
    title: "Doors, coffee, name badges",
    kind: "break",
    day: 1,
    start: "09:00",
    end: "09:30",
    roomId: null,
    speakerIds: [],
    summary: "Registration in the Foundry. Coffee is in the Yard and is genuinely good.",
    topics: [],
  },
  {
    id: "d1-02",
    slug: "nothing-is-ever-finished",
    title: "Nothing is ever finished",
    kind: "keynote",
    day: 1,
    start: "09:30",
    end: "10:30",
    roomId: null,
    speakerIds: ["s01"],
    summary:
      "An opening argument that the finished thing is a fiction the funding model requires, and that everything we build is really a subscription nobody costed.",
    body: [
      "We describe work as shipped, delivered, completed, opened. Every one of those words describes a moment that does not exist. The bridge opens and immediately begins to need painting. The system launches and immediately begins to drift from the assumptions it was built on. The building is handed over and the handover is the first day of the part that lasts eighty years.",
      "This talk is about why we keep using the vocabulary anyway, who benefits from it, and what changes when an organisation is honest with itself that it has not bought a thing but committed to an obligation. It draws on eleven years of bridge inspection reports and a great many meetings that went badly.",
    ],
    topics: ["Infrastructure", "Care"],
  },
  {
    id: "d1-03",
    slug: "coffee-day-one-morning",
    title: "Coffee",
    kind: "break",
    day: 1,
    start: "10:30",
    end: "11:00",
    roomId: null,
    speakerIds: [],
    summary: "In the Yard, under cover.",
    topics: [],
  },
  {
    id: "d1-04",
    slug: "what-the-water-main-knew",
    title: "What the water main knew",
    kind: "talk",
    day: 1,
    start: "11:00",
    end: "11:45",
    roomId: "foundry",
    speakerIds: ["s03"],
    summary:
      "Four thousand miles of pipe, a fifth of it with no surviving installation record, and what leak data tells you that the map does not.",
    body: [
      "A water network is one of the few pieces of infrastructure that reports on itself continuously, if you are willing to listen to it. Pressure, flow and acoustic data describe a system that the drawings stopped describing accurately decades ago.",
      "This talk covers what a leak-detection programme actually finds, why the pipes that fail are so rarely the pipes anyone worried about, and the uncomfortable finding that a pipe which has not failed is not the same as a pipe that is fine.",
    ],
    topics: ["Infrastructure"],
  },
  {
    id: "d1-05",
    slug: "your-dependencies-are-someones-weekend",
    title: "Your dependencies are someone's weekend",
    kind: "talk",
    day: 1,
    start: "11:00",
    end: "11:45",
    roomId: "boiler",
    speakerIds: ["s04"],
    summary:
      "A maintainer of three very widely used libraries on what the arrangement costs, with numbers rather than grievance.",
    body: [
      "Every large software organisation depends on work done in evenings by people it has never contacted. This is not framed here as a moral failing but as a supply chain with a single point of failure in it, which is a thing those organisations already know how to think about.",
      "Includes download figures, issue-response times, the honest cost of a security disclosure handled by one person, and several things companies have done that genuinely helped.",
    ],
    topics: ["Software", "Repair"],
  },
  {
    id: "d1-06",
    slug: "reading-a-building",
    title: "Reading a building before you open it up",
    kind: "talk",
    day: 1,
    start: "11:00",
    end: "11:45",
    roomId: "drawing",
    speakerIds: ["s13"],
    summary:
      "How to work out what a structure is doing, and what has already been done to it, before anybody specifies anything.",
    body: [
      "Most of what goes wrong on a repair project was decided in the first fortnight, before there was enough information to decide anything. This talk is a practical account of the survey work that should happen first: what to measure, what to open, what to leave, and how to read previous interventions.",
      "The running example is a 1930s civic building where four separate improvements had each solved a problem by creating the next one.",
    ],
    topics: ["Buildings"],
  },
  {
    id: "d1-07",
    slug: "sharpening",
    title: "Sharpening, and why the tool outlives you",
    kind: "talk",
    day: 1,
    start: "11:00",
    end: "11:45",
    roomId: "yard",
    speakerIds: ["s06"],
    summary:
      "A toolmaker on edge geometry, and on the design decision to make something that expects to be reground for a century.",
    body: [
      "A tool designed to be resharpened is a different object from one designed to be replaced, and the difference is visible in the steel before it is visible in the catalogue. This session covers how to tell them apart.",
      "Practical throughout: bring a chisel if you have one, though there is no bench in this room and the hands-on version is Wednesday afternoon.",
    ],
    topics: ["Repair"],
  },
  {
    id: "d1-08",
    slug: "the-people-who-keep-the-trains-running",
    title: "The people who keep the trains running",
    kind: "talk",
    day: 1,
    start: "11:55",
    end: "12:40",
    roomId: "foundry",
    speakerIds: ["s10"],
    summary:
      "Nineteen years of night gangs on regional track, and what the job actually consists of between the hours everyone else is asleep.",
    body: [
      "Track maintenance is planned in possessions — fixed windows, usually overnight, in which a section of railway belongs to the gang rather than to the timetable. Everything about the work is shaped by that constraint.",
      "This is an account of how the planning really goes, why the third hour is the dangerous one, and what nineteen years of doing it has taught one supervisor about training the people who come next.",
    ],
    topics: ["Infrastructure", "Care"],
  },
  {
    id: "d1-09",
    slug: "deprecation-is-a-promise",
    title: "Deprecation is a promise, not an announcement",
    kind: "talk",
    day: 1,
    start: "11:55",
    end: "12:40",
    roomId: "boiler",
    speakerIds: ["s24"],
    summary:
      "Three large deprecations, the first of which went badly, and the difference between telling people and giving them somewhere to go.",
    body: [
      "A deprecation notice describes the present. A deprecation is a commitment about the future: that a replacement exists, that it is at least as good, that somebody will help, and that the date will not move twice.",
      "This talk works through what each of those costs, using three real migrations of increasing size and decreasing drama.",
    ],
    topics: ["Software", "Standards"],
  },
  {
    id: "d1-10",
    slug: "the-archive-that-could-not-be-opened",
    title: "The archive that could not be opened",
    kind: "talk",
    day: 1,
    start: "11:55",
    end: "12:40",
    roomId: "drawing",
    speakerIds: ["s09"],
    summary:
      "Thirty years of industrial records in a format that was readable for three decades and then, quite suddenly, was not.",
    body: [
      "Format obsolescence is usually described as a slow decline. In practice it arrives as a cliff: the software is fine, the software is fine, the software will not run on anything you can still buy.",
      "An account of recovering a complete works archive, what it cost, what was lost anyway, and the migration policy that came out of it.",
    ],
    topics: ["Archives", "Software"],
  },
  {
    id: "d1-11",
    slug: "lunch-day-one",
    title: "Lunch",
    kind: "break",
    day: 1,
    start: "12:40",
    end: "13:40",
    roomId: null,
    speakerIds: [],
    summary: "In the Yard. Vegetarian by default, everything labelled.",
    topics: [],
  },
  {
    id: "d1-12",
    slug: "a-lock-taken-apart",
    title: "Hands on: a lock, taken apart and put back",
    kind: "workshop",
    day: 1,
    start: "13:40",
    end: "15:10",
    roomId: "drawing",
    speakerIds: ["s06"],
    summary:
      "Ninety minutes, one mortice lock each, and the discovery that almost nothing inside it is worn out.",
    body: [
      "Every participant gets a working lock, a bench, and the tools. It comes apart, gets cleaned, and goes back together, which for most people is the first time they have seen the inside of a mechanism they use daily.",
      "The point is not locksmithing. It is the specific feeling of finding that a thing you assumed was beyond you has eleven parts in it, four of which do nothing but hold the others in place.",
    ],
    capacity: 24,
    soldOut: true,
    topics: ["Repair"],
  },
  {
    id: "d1-13",
    slug: "rust-and-other-honest-materials",
    title: "Rust, and other honest materials",
    kind: "talk",
    day: 1,
    start: "13:40",
    end: "14:25",
    roomId: "foundry",
    speakerIds: ["s05"],
    summary:
      "In praise of materials that tell you how they are doing, and a warning about the ones that fail without warning.",
    body: [
      "Some materials degrade legibly. Timber goes soft where the water is, steel stains before it thins, lime mortar fails before the stone does. Others hold their appearance until the moment they do not, which makes them a maintenance problem disguised as a maintenance solution.",
      "This talk argues for legibility as a specification criterion in its own right, and looks at several buildings where it was traded away for a twenty-year guarantee.",
    ],
    topics: ["Buildings", "Repair"],
  },
  {
    id: "d1-14",
    slug: "on-call-is-a-design-decision",
    title: "On-call is a design decision, not a rota",
    kind: "talk",
    day: 1,
    start: "13:40",
    end: "14:25",
    roomId: "boiler",
    speakerIds: ["s08"],
    summary:
      "Eleven years of carrying a pager across three industries, and the argument that most escalation policies are a way of not deciding something.",
    body: [
      "When a system pages a human at three in the morning, a decision has been made about what that system is allowed to do on its own. Most organisations have never written that decision down, which is why their rota keeps growing.",
      "Covers escalation design, the real cost of a false page, and why 'add it to the runbook' is frequently the wrong response to an incident.",
    ],
    topics: ["Software", "Care"],
  },
  {
    id: "d1-15",
    slug: "what-a-repair-cafe-fixes",
    title: "What a repair café actually fixes",
    kind: "talk",
    day: 1,
    start: "13:40",
    end: "14:25",
    roomId: "yard",
    speakerIds: ["s21"],
    summary:
      "Six years of records from a monthly repair café, which turn out to be a small and quite surprising dataset.",
    body: [
      "About a third of everything brought in is fixed with a part costing under two dollars. Another third cannot be fixed because the part does not exist at any price. The last third was never broken.",
      "This talk goes through the numbers, and then through the thing the numbers do not capture, which is what happens to somebody's relationship with their possessions the first time they watch one be opened.",
    ],
    topics: ["Repair", "Care"],
  },
  {
    id: "d1-16",
    slug: "forty-years-of-a-municipal-swimming-pool",
    title:
      "What forty years of maintenance records from a single municipal swimming pool can tell you about how institutions decide what is worth keeping",
    kind: "talk",
    day: 1,
    start: "14:35",
    end: "15:20",
    roomId: "foundry",
    speakerIds: ["s22"],
    summary:
      "One 1904 building, every maintenance record since 1998, and six separate plans to close it that it has now outlived.",
    body: [
      "The baths should have closed in 2003, and in 2009, and in 2016. Each time the case for closure was built on a maintenance backlog, and each time the backlog was a number somebody had chosen rather than measured.",
      "This talk reconstructs those decisions from the building's own paperwork, and makes an argument about who gets to define what a repair costs.",
    ],
    topics: ["Buildings", "Archives"],
  },
  {
    id: "d1-17",
    slug: "two-hundred-years-of-the-same-roof",
    title: "Two hundred years of the same roof",
    kind: "talk",
    day: 1,
    start: "14:35",
    end: "15:20",
    roomId: "boiler",
    speakerIds: ["s29"],
    summary:
      "A fourth-generation roofer with the family ledgers back to 1871, on what continuity of care actually looks like as a business.",
    body: [
      "The same firm has worked on some of these roofs four times, at intervals of roughly fifty years. The ledgers record what was done, what it cost, and — most usefully — what the previous generation got wrong.",
      "An argument that the useful unit of maintenance knowledge is longer than a career, and a practical account of how a small firm holds knowledge across one.",
    ],
    topics: ["Buildings", "Archives"],
  },
  {
    id: "d1-18",
    slug: "field-notes-from-a-very-old-canal",
    title: "Field notes from a very old canal",
    kind: "talk",
    day: 1,
    start: "14:35",
    end: "15:20",
    roomId: "yard",
    speakerIds: ["s18"],
    summary:
      "Eleven miles of 1798 waterway, kept going on Victorian drawings and forty years of handwritten observation.",
    body: [
      "The engineering drawings are excellent and describe a canal that no longer exists in several important respects. The gap between the two is held in one warden's notebooks.",
      "This session is about that gap: how local knowledge accumulates, what happens to it when a post turns over, and one attempt to write it down before it is too late.",
    ],
    topics: ["Infrastructure", "Archives"],
  },
  {
    id: "d1-19",
    slug: "coffee-day-one-afternoon",
    title: "Coffee",
    kind: "break",
    day: 1,
    start: "15:20",
    end: "15:45",
    roomId: null,
    speakerIds: [],
    summary: "In the Yard.",
    topics: [],
  },
  {
    id: "d1-20",
    slug: "legacy-is-a-compliment",
    title: "Legacy is a compliment",
    kind: "talk",
    day: 1,
    start: "15:45",
    end: "16:30",
    roomId: "foundry",
    speakerIds: ["s02"],
    summary:
      "A defence of old systems, on the grounds that nothing gets to be old without having been right about something.",
    body: [
      "A codebase that has been in production for twenty years has survived twenty years of things going wrong. That is a form of evidence, and it is not evidence the replacement has.",
      "This talk is about reading that evidence: how to find the load-bearing weirdness, how to tell an accident from a decision, and how to work out what a system knows that nobody working on it does.",
    ],
    topics: ["Software"],
  },
  {
    id: "d1-21",
    slug: "standards-move-slowly",
    title: "Standards move slowly for a reason",
    kind: "talk",
    day: 1,
    start: "15:45",
    end: "16:30",
    roomId: "boiler",
    speakerIds: ["s12"],
    summary:
      "A standards editor on watching a single clause take four years, and why that was roughly the right amount of time.",
    body: [
      "Consensus processes are widely described as broken by people who have not sat in one. This talk is a sympathetic but unsentimental account of how agreement is actually reached between parties with genuinely incompatible interests.",
      "It includes the clause in question, the four years, and an honest assessment of the two years that were wasted.",
    ],
    topics: ["Standards"],
  },
  {
    id: "d1-22",
    slug: "conservation-joinery",
    title: "Conservation joinery: what to leave alone",
    kind: "talk",
    day: 1,
    start: "15:45",
    end: "16:30",
    roomId: "drawing",
    speakerIds: ["s23"],
    summary:
      "A timber conservator on the rule that the second repair is usually the one that does the damage.",
    body: [
      "The first repair is done because something failed. The second is done because the first one looked untidy, and it is the second that removes the original material.",
      "This session covers reversibility, honest patching, and the difficult conversation in which a client is persuaded that the correct intervention is a smaller one than they are paying for.",
    ],
    topics: ["Buildings", "Repair"],
  },
  {
    id: "d1-23",
    slug: "drinks-day-one",
    title: "Drinks in the Yard",
    kind: "break",
    day: 1,
    start: "16:40",
    end: "17:30",
    roomId: null,
    speakerIds: [],
    summary: "Included in every ticket. Non-alcoholic options are not an afterthought.",
    topics: [],
  },

  // ── Day two — Who fixes it ─────────────────────────────────────────
  {
    id: "d2-01",
    slug: "on-call-for-the-sewer",
    title: "Who is actually on call for the sewer",
    kind: "talk",
    day: 2,
    start: "09:00",
    end: "09:45",
    roomId: "foundry",
    speakerIds: ["s14"],
    summary:
      "Nine hundred miles of sewer, the crews who get woken up for it, and a low tolerance for asset software written by people who have never been down one.",
    body: [
      "Every municipal asset register describes a network. Very few of them describe the work, which happens at night, in weather, by people whose names do not appear in the system.",
      "This talk is about that mismatch, and about what an asset-management tool would look like if it had been designed with a crew leader in the room.",
    ],
    topics: ["Infrastructure", "Software"],
  },
  {
    id: "d2-02",
    slug: "maintenance-as-care-work",
    title: "Maintenance as care work",
    kind: "talk",
    day: 2,
    start: "09:00",
    end: "09:45",
    roomId: "boiler",
    speakerIds: ["s11"],
    summary:
      "Why work that is invisible when done correctly is counted as neither maintenance nor care, and what that costs the people doing it.",
    body: [
      "Six people whose jobs consist entirely of preventing things from happening. None of them can point to an output. All of them are evaluated on one.",
      "The talk draws the parallel with domestic and care labour deliberately, and follows it to its uncomfortable conclusion about who ends up doing this work and what it pays.",
    ],
    topics: ["Care"],
  },
  {
    id: "d2-03",
    slug: "cataloguing-is-maintenance",
    title: "Cataloguing is maintenance",
    kind: "talk",
    day: 2,
    start: "09:00",
    end: "09:45",
    roomId: "drawing",
    speakerIds: ["s07"],
    summary:
      "Ninety thousand objects, four staff, and the point at which an uncatalogued collection stops being a collection.",
    body: [
      "An object nobody can find is not preserved in any sense that matters. The catalogue is not a description of the collection; past a certain size it is the only thing making it one.",
      "This talk is about resourcing that argument, and about a backlog measured in decades rather than months.",
    ],
    topics: ["Archives", "Care"],
  },
  {
    id: "d2-04",
    slug: "handover-the-most-dangerous-hour",
    title: "Handover: the most dangerous hour",
    kind: "talk",
    day: 2,
    start: "09:55",
    end: "10:40",
    roomId: "foundry",
    speakerIds: ["s26"],
    summary:
      "An inspection consultant on the observation that things fail at shift changes, project handovers and contract transitions far more than at any other time.",
    body: [
      "The pattern holds across industries with suspicious consistency: the failure happens when responsibility moves. Not while it is held badly, but while it is being passed.",
      "This talk looks at handover as a designed process rather than an administrative one, and at the small number of protocols that demonstrably work.",
    ],
    topics: ["Standards", "Care"],
  },
  {
    id: "d2-05",
    slug: "the-maintainers-inbox",
    title: "The maintainer's inbox",
    kind: "talk",
    day: 2,
    start: "09:55",
    end: "10:40",
    roomId: "boiler",
    speakerIds: ["s04"],
    summary:
      "What actually arrives, in what proportion, and the triage system that made an unmaintainable volume maintainable again.",
    body: [
      "Bug reports are a minority of the inbox. The majority is questions, entitlement, duplicates, and a small and precious stream of genuinely excellent contributions that arrive with no fanfare at all.",
      "A practical session on triage, on templates that actually reduce load, and on the specific wording that turns an angry issue into a useful one.",
    ],
    topics: ["Software", "Care"],
  },
  {
    id: "d2-06",
    slug: "bicycles-and-the-spare-part",
    title: "Bicycles and the politics of the spare part",
    kind: "talk",
    day: 2,
    start: "09:55",
    end: "10:40",
    roomId: "yard",
    speakerIds: ["s16"],
    summary:
      "Three thousand repairs a year, mostly for people who could not otherwise get to work, and a wall of parts nobody makes any more.",
    body: [
      "A bottom bracket standard is an infrastructure decision. It determines, twenty years later, whether a bicycle is worth repairing or is scrap, and therefore whether somebody has a way to get to a job.",
      "This talk is about that chain of consequence, told from a co-operative workshop that keeps a physical record of every standard that has been abandoned.",
    ],
    topics: ["Repair"],
  },
  {
    id: "d2-07",
    slug: "coffee-day-two-morning",
    title: "Coffee",
    kind: "break",
    day: 2,
    start: "10:40",
    end: "11:00",
    roomId: null,
    speakerIds: [],
    summary: "In the Yard. Short break — the 11:00 sessions start promptly.",
    topics: [],
  },
  {
    id: "d2-08",
    slug: "nobody-is-coming",
    title: "Nobody is coming: municipal software after the grant ends",
    kind: "talk",
    day: 2,
    start: "11:00",
    end: "11:45",
    roomId: "foundry",
    speakerIds: ["s15"],
    summary:
      "Nine inherited systems, four of them buried, and what happens to civic software on the day the funding that built it runs out.",
    body: [
      "Grant-funded software is specified, built, launched and celebrated inside a window that is always shorter than the life of the problem. What follows is not decline exactly; it is a slow discovery that no line in anyone's budget covers this.",
      "This talk covers the four systems that were shut down, the five that survived, and the single structural difference between the two groups.",
    ],
    topics: ["Software", "Infrastructure"],
  },
  {
    id: "d2-09",
    slug: "what-a-good-runbook-looks-like",
    title: "What a good runbook looks like",
    kind: "talk",
    day: 2,
    start: "11:00",
    end: "11:45",
    roomId: "boiler",
    speakerIds: ["s19"],
    summary:
      "Documentation rot measured rather than complained about, and the specific properties of the procedures that survive contact with an incident.",
    body: [
      "A runbook is read exactly once per emergency, by somebody frightened, at an hour they did not choose. Almost nothing written in normal conditions survives that test.",
      "This session covers what does: decision points over prose, exact commands over descriptions, and an explicit statement of what to do when the runbook is wrong.",
    ],
    topics: ["Software", "Standards"],
  },
  {
    id: "d2-10",
    slug: "who-owns-the-road",
    title: "Who owns the road",
    kind: "talk",
    day: 2,
    start: "11:00",
    end: "11:45",
    roomId: "drawing",
    speakerIds: ["s27"],
    summary:
      "A highways engineer maps the roads that four separate bodies each believe somebody else is responsible for. The map is the talk.",
    body: [
      "Ambiguous ownership is not a rare edge case in a road network; in one county it accounts for a measurable fraction of the surface. Every one of those stretches degrades until it becomes an emergency, at which point ownership is resolved quickly and expensively.",
      "The talk presents the map, the method used to build it, and what happened when it was shown to the four bodies concerned.",
    ],
    topics: ["Infrastructure", "Standards"],
  },
  {
    id: "d2-11",
    slug: "night-gangs",
    title: "Night gangs",
    kind: "talk",
    day: 2,
    start: "11:00",
    end: "11:45",
    roomId: "yard",
    speakerIds: ["s10"],
    summary:
      "A short, practical session on planning a possession, from a supervisor who has trained a third of his division.",
    body: [
      "Everything about track work is shaped by the possession window: how long you have, what you can stage in advance, and what you do when the third hour arrives and the plan has already changed.",
      "Deliberately concrete, and deliberately outdoors.",
    ],
    topics: ["Infrastructure"],
  },
  {
    id: "d2-12",
    slug: "rewriting-is-not-maintenance",
    title: "Rewriting is not maintenance",
    kind: "talk",
    day: 2,
    start: "11:55",
    end: "12:40",
    roomId: "foundry",
    speakerIds: ["s02"],
    summary:
      "The memo, expanded, defended, and considerably qualified in the light of the four years since it circulated.",
    body: [
      "The original argument was that a rewrite discards the accumulated corrections of everyone who came before, and that this is almost always underpriced. That argument still holds.",
      "What it got wrong was the implication that rewriting is therefore rarely correct. This talk sets out the cases where it genuinely is, and the test for telling them apart.",
    ],
    topics: ["Software"],
  },
  {
    id: "d2-13",
    slug: "paying-people-to-do-nothing-visible",
    title: "Paying people to do nothing visible",
    kind: "talk",
    day: 2,
    start: "11:55",
    end: "12:40",
    roomId: "boiler",
    speakerIds: ["s11"],
    summary:
      "The management problem at the heart of all preventive work: how do you evaluate somebody whose success looks like an absence?",
    body: [
      "Every metric available to a manager measures activity. Preventive maintenance produces no activity when it is working, and a great deal of activity when it has failed — so the measurements point exactly the wrong way.",
      "This talk looks at organisations that have solved this, which are fewer than you would hope and more than none.",
    ],
    topics: ["Care", "Standards"],
  },
  {
    id: "d2-14",
    slug: "documentation-rot",
    title: "Documentation rot",
    kind: "talk",
    day: 2,
    start: "11:55",
    end: "12:40",
    roomId: "drawing",
    speakerIds: ["s19"],
    summary:
      "Two hundred engineers writing into one platform, a published internal decay report, and the finding that rot is not evenly distributed.",
    body: [
      "Documentation does not decay at a constant rate. It decays where the system changes, which means the pages most likely to be wrong are exactly the pages most likely to be read.",
      "The report, the method, and the three interventions that moved the number.",
    ],
    topics: ["Software", "Archives"],
  },
  {
    id: "d2-15",
    slug: "lunch-day-two",
    title: "Lunch",
    kind: "break",
    day: 2,
    start: "12:40",
    end: "13:40",
    roomId: null,
    speakerIds: [],
    summary: "In the Yard.",
    topics: [],
  },
  {
    id: "d2-16",
    slug: "writing-a-runbook-workshop",
    title: "Hands on: writing a runbook someone else can follow",
    kind: "workshop",
    day: 2,
    start: "13:40",
    end: "15:10",
    roomId: "drawing",
    speakerIds: ["s08"],
    summary:
      "Ninety minutes. Bring a procedure you own. Leave with one somebody else has successfully executed in front of you.",
    body: [
      "The exercise is simple and reliably humbling: write the procedure, hand it to a stranger, and watch them try to follow it without speaking to you.",
      "Everybody's first draft fails. The session is about the second one.",
    ],
    capacity: 30,
    topics: ["Software", "Standards"],
  },
  {
    id: "d2-17",
    slug: "the-backlog-is-a-moral-document",
    title: "The maintenance backlog is a moral document",
    kind: "talk",
    day: 2,
    start: "13:40",
    end: "14:25",
    roomId: "foundry",
    speakerIds: ["s17"],
    summary:
      "A public-finance analyst on what a deferred-maintenance list actually records, which is a sequence of decisions about who waits.",
    body: [
      "A backlog is usually presented as a technical inventory. It is nothing of the kind: it is an ordered list, and the ordering encodes which neighbourhoods, which buildings and which people are asked to wait longest.",
      "The talk works through three real capital budgets and asks the ordering question of each.",
    ],
    topics: ["Infrastructure", "Care"],
  },
  {
    id: "d2-18",
    slug: "small-museums-big-collections",
    title: "Small museums, big collections",
    kind: "talk",
    day: 2,
    start: "13:40",
    end: "14:25",
    roomId: "boiler",
    speakerIds: ["s25"],
    summary:
      "A hundred and forty institutions with fewer than five staff each — most of the museums in the country and almost none of the funding.",
    body: [
      "The sector's statistics are dominated by a handful of large institutions. The sector's collections are not. This talk sets out the actual distribution and what it implies for how support is designed.",
      "Direct about what volunteers can and cannot be asked to hold up, and about the collections currently being held up by exactly one person.",
    ],
    topics: ["Archives", "Care"],
  },
  {
    id: "d2-19",
    slug: "insurance-as-an-accidental-regulator",
    title: "Insurance as an accidental regulator",
    kind: "talk",
    day: 2,
    start: "14:35",
    end: "15:20",
    roomId: "foundry",
    speakerIds: ["s20"],
    summary:
      "An underwriter on being one of the few people whose job depends on maintenance genuinely happening, and on what that leverage is and is not good for.",
    body: [
      "Where regulation is absent or unenforced, insurance frequently ends up setting the actual standard — not because anybody designed it that way, but because premiums are the only consequence that arrives reliably.",
      "This talk is honest about the limits: insurers price what they can measure, which is not the same as what matters.",
    ],
    topics: ["Standards", "Infrastructure"],
  },
  {
    id: "d2-20",
    slug: "inspection-regimes-that-inspect-nothing",
    title: "Inspection regimes that inspect nothing",
    kind: "talk",
    day: 2,
    start: "14:35",
    end: "15:20",
    roomId: "boiler",
    speakerIds: ["s26"],
    summary:
      "Designing an inspection regime, and then going back seven years later to find out whether it inspected anything. Frequently it did not.",
    body: [
      "A regime that is followed to the letter can still be worthless, and this is more common than the profession finds comfortable. The failure is usually in what the checklist made easy to record rather than in compliance.",
      "Three regimes, three follow-up studies, and what the two that worked had in common.",
    ],
    topics: ["Standards"],
  },
  {
    id: "d2-21",
    slug: "the-second-repair",
    title: "The second repair is the one that does the damage",
    kind: "talk",
    day: 2,
    start: "14:35",
    end: "15:20",
    roomId: "yard",
    speakerIds: ["s23"],
    summary:
      "A timber conservator's rule of thumb, examined across a dozen buildings to see whether it survives contact with evidence.",
    body: [
      "The first intervention responds to a failure and is usually minimal. The second responds to the appearance of the first, and it is the tidying-up that removes original material.",
      "Twelve buildings, photographed before and after both interventions, and the one case where the rule was wrong.",
    ],
    topics: ["Buildings", "Repair"],
  },
  {
    id: "d2-22",
    slug: "coffee-day-two-afternoon",
    title: "Coffee",
    kind: "break",
    day: 2,
    start: "15:20",
    end: "15:45",
    roomId: null,
    speakerIds: [],
    summary: "In the Yard.",
    topics: [],
  },
  {
    id: "d2-23",
    slug: "who-pays-for-the-boring-part",
    title: "Panel: who pays for the boring part",
    kind: "panel",
    day: 2,
    start: "15:45",
    end: "16:45",
    roomId: "foundry",
    speakerIds: ["s01", "s17", "s30"],
    summary:
      "A funder, an auditor and a director argue about the actual mechanism by which ongoing work gets money. Chaired, and not gentle.",
    body: [
      "Everyone agrees maintenance is underfunded. Almost nobody agrees on why, and the disagreement is not really about money — it is about which institution is supposed to hold a forty-year obligation when none of them has a forty-year budget.",
      "Sixty minutes, three positions that genuinely conflict, and questions from the floor for the last twenty.",
    ],
    topics: ["Care", "Standards", "Infrastructure"],
  },
  {
    id: "d2-24",
    slug: "reception-day-two",
    title: "Reception in the Yard",
    kind: "break",
    day: 2,
    start: "17:00",
    end: "18:00",
    roomId: null,
    speakerIds: [],
    summary: "Food, and the Ironhouse's own beer. Included in every ticket.",
    topics: [],
  },

  // ── Day three — What it costs ──────────────────────────────────────
  {
    id: "d3-01",
    slug: "the-last-person-who-knew",
    title: "The last person who knew how it worked",
    kind: "talk",
    day: 3,
    start: "09:30",
    end: "10:15",
    roomId: "foundry",
    speakerIds: ["s09"],
    summary:
      "Institutional knowledge that exists in exactly one head, how to find out that this is the situation, and what to do in the eighteen months you have.",
    body: [
      "Single points of human failure are rarely identified in advance, because the person concerned does not experience their knowledge as unusual. They experience it as the job.",
      "This talk covers three methods for finding these people before they retire, and one account of what happened when nobody did.",
    ],
    topics: ["Archives", "Care"],
  },
  {
    id: "d3-02",
    slug: "grant-cycles-versus-roof-cycles",
    title: "Grant cycles versus roof cycles",
    kind: "talk",
    day: 3,
    start: "09:30",
    end: "10:15",
    roomId: "boiler",
    speakerIds: ["s30"],
    summary:
      "A grants officer, candidly, on the mismatch between a three-year funding cycle and a forty-year roof — and on trying to change it from inside.",
    body: [
      "Foundations fund projects because projects can be evaluated. Maintenance cannot be evaluated in the same way, so it does not get funded, so it becomes a project again once the failure is severe enough to photograph.",
      "This is an account of the internal argument for endowment-style maintenance funding, including the parts of it that have not worked.",
    ],
    topics: ["Care", "Buildings"],
  },
  {
    id: "d3-03",
    slug: "what-we-spent-on-the-roof",
    title: "What we spent on the roof, 1998 to 2026",
    kind: "talk",
    day: 3,
    start: "09:30",
    end: "10:15",
    roomId: "drawing",
    speakerIds: ["s22"],
    summary:
      "One building, twenty-eight years of invoices, and the comparison with what a full replacement would have cost in each of those years.",
    body: [
      "Every year the replacement was deferred, and every year the deferral was defensible on its own terms. The interesting question is what the sequence of individually defensible decisions added up to.",
      "The numbers are on the slide, adjusted, with the counterfactual alongside them.",
    ],
    topics: ["Buildings", "Archives"],
  },
  {
    id: "d3-04",
    slug: "insurance-and-the-uninsurable",
    title: "What happens when it becomes uninsurable",
    kind: "talk",
    day: 3,
    start: "10:25",
    end: "11:10",
    roomId: "foundry",
    speakerIds: ["s20"],
    summary:
      "The point at which a maintained asset stops being priceable, what precedes it, and how much warning anyone actually gets.",
    body: [
      "Withdrawal of cover is the clearest possible signal that a maintenance regime has failed, and it arrives late, all at once, and with no appeal.",
      "This session works through the leading indicators, which are visible several years earlier to anyone who knows to look.",
    ],
    topics: ["Standards", "Infrastructure"],
  },
  {
    id: "d3-05",
    slug: "the-true-cost-of-a-rewrite",
    title: "The true cost of a rewrite",
    kind: "talk",
    day: 3,
    start: "10:25",
    end: "11:10",
    roomId: "boiler",
    speakerIds: ["s24"],
    cancelled: "Withdrawn — the speaker is unwell. The room is open as quiet space.",
    summary:
      "A cost model for replacement built from three migrations, including the two that overran.",
    body: [
      "This session has been withdrawn. It is kept on the schedule rather than removed because people have it in their plans, and a session that silently disappears is indistinguishable from one you misremembered.",
    ],
    topics: ["Software"],
  },
  {
    id: "d3-06",
    slug: "volunteers-are-not-a-funding-model",
    title: "Volunteers are not a funding model",
    kind: "talk",
    day: 3,
    start: "10:25",
    end: "11:10",
    roomId: "yard",
    speakerIds: ["s25"],
    summary:
      "What volunteer labour can genuinely sustain, what it cannot, and the specific failure mode of building a service on it anyway.",
    body: [
      "Volunteers are excellent at bounded, sociable, visible work. They are structurally poor at obligations that must be met on a bad Tuesday in February for the next fifteen years, and no amount of goodwill changes that.",
      "This talk is not against volunteering. It is against costing a permanent obligation at zero.",
    ],
    topics: ["Care"],
  },
  {
    id: "d3-07",
    slug: "coffee-day-three",
    title: "Coffee",
    kind: "break",
    day: 3,
    start: "11:10",
    end: "11:30",
    roomId: null,
    speakerIds: [],
    summary: "In the Yard. Last one.",
    topics: [],
  },
  {
    id: "d3-08",
    slug: "deferred-maintenance-compounding",
    title: "Deferred maintenance, compounding",
    kind: "talk",
    day: 3,
    start: "11:30",
    end: "12:15",
    roomId: "foundry",
    speakerIds: ["s17"],
    summary:
      "The argument that deferred maintenance is a liability and belongs on a balance sheet, delivered by the person who has been making it for six years.",
    body: [
      "A deferral is a loan taken out against a building, at an interest rate set by physics rather than by a lender. It compounds, it is not recorded anywhere, and it comes due.",
      "The talk sets out how it would actually be accounted for, and what would change politically if it were.",
    ],
    topics: ["Infrastructure", "Standards"],
  },
  {
    id: "d3-09",
    slug: "right-to-repair-three-years-on",
    title: "Right to repair, three years on",
    kind: "talk",
    day: 3,
    start: "11:30",
    end: "12:15",
    roomId: "boiler",
    speakerIds: ["s28"],
    summary:
      "What the legislation now requires, set carefully against what has actually changed on a workshop bench.",
    body: [
      "Parts availability, documentation and tooling were all addressed. Two of the three have moved. The talk is precise about which.",
      "It also covers the compliance strategies that technically satisfy the requirement while leaving a repair no more possible than before.",
    ],
    topics: ["Repair", "Standards"],
  },
  {
    id: "d3-10",
    slug: "the-tools-outlive-the-owner",
    title: "Tools that outlive their owners",
    kind: "talk",
    day: 3,
    start: "11:30",
    end: "12:15",
    roomId: "drawing",
    speakerIds: ["s06"],
    summary:
      "What happens to a workshop when the person whose workshop it was is gone, and why so much of it is scrapped.",
    body: [
      "A well-kept set of tools represents decades of accumulated judgement about what is worth having. Almost none of that judgement survives the estate sale.",
      "A short talk about the mechanics of dispersal, and about the small number of institutions doing it well.",
    ],
    topics: ["Repair", "Archives"],
  },
  {
    id: "d3-11",
    slug: "lunch-day-three",
    title: "Lunch",
    kind: "break",
    day: 3,
    start: "12:15",
    end: "13:15",
    roomId: null,
    speakerIds: [],
    summary: "In the Yard.",
    topics: [],
  },
  {
    id: "d3-12",
    slug: "the-long-now-of-the-ordinary",
    title: "The long now of the ordinary",
    kind: "keynote",
    day: 3,
    start: "13:15",
    end: "14:00",
    roomId: null,
    speakerIds: ["s11"],
    summary:
      "A closing argument for the unglamorous, the recurring and the barely noticed, and for the people who have spent three days here talking about them.",
    body: [
      "The monuments get the plaques. The thing that actually keeps a society running is a very large number of people doing something small and repetitive at the correct interval, and almost none of them will be thanked for it.",
      "A closing keynote about what it would take to notice, and about why noticing is a political act rather than a sentimental one.",
    ],
    topics: ["Care"],
  },
];
