import type { Speaker } from "./types";

/**
 * Thirty invented people.
 *
 * There are no photographs in this template and that is a decision
 * rather than an omission — CONVENTIONS §6 rules out attaching a stock
 * portrait to an invented person, and thirty of them would be thirty
 * real faces standing behind quotes nobody said. They are drawn as
 * monograms, which is also what most conference sites fall back to when
 * half the speakers have not sent a headshot yet.
 */
export const speakers: Speaker[] = [
  {
    id: "s01",
    slug: "rosalind-achebe",
    name: "Rosalind Achebe",
    role: "Director",
    org: "Institute for Long Repair",
    place: "Chicago",
    initials: "RA",
    bio: [
      "Rosalind spent eleven years as a bridge inspector for a state transport department before deciding the interesting problem was not the steel but the paperwork around it.",
      "She now runs a small institute that studies how organisations decide what is worth keeping, and writes an annual report that almost nobody in government enjoys receiving.",
    ],
  },
  {
    id: "s02",
    slug: "tomas-erdely",
    name: "Tomas Erdely",
    role: "Principal engineer",
    org: "Kestrel Works",
    place: "Cleveland",
    initials: "TE",
    bio: [
      "Tomas has spent most of his career on codebases older than the people maintaining them, mostly in logistics and municipal billing.",
      "He is the author of a widely circulated internal memo titled 'Rewriting Is Not Maintenance', which he has since had to defend at some length.",
    ],
  },
  {
    id: "s03",
    slug: "priya-raghunathan",
    name: "Priya Raghunathan",
    role: "Water systems lead",
    org: "Allegheny Regional Water",
    place: "Pittsburgh",
    initials: "PR",
    bio: [
      "Priya runs the leak-detection programme for a network with about 4,000 miles of pipe in it, roughly a fifth of which predates any surviving record of its installation.",
      "She is unusually good at explaining why a pipe that has not failed is not the same as a pipe that is fine.",
    ],
  },
  {
    id: "s04",
    slug: "declan-moore",
    name: "Declan Moore",
    role: "Open source maintainer",
    org: "Independent",
    place: "Galway",
    initials: "DM",
    bio: [
      "Declan maintains three libraries that are, between them, a dependency of a large fraction of the packages published in his ecosystem.",
      "He does this in the evenings, and has strong and well-evidenced opinions about what that arrangement costs everyone involved.",
    ],
  },
  {
    id: "s05",
    slug: "hanne-vestergaard",
    name: "Hanne Vestergaard",
    role: "Conservation architect",
    org: "Vestergaard & Ma",
    place: "Copenhagen",
    initials: "HV",
    bio: [
      "Hanne works almost exclusively on buildings that somebody else has already tried to improve, which she describes as 'archaeology with a deadline'.",
      "Her practice has a standing rule that no intervention is specified in the first two weeks of a project.",
    ],
  },
  {
    id: "s06",
    slug: "marcus-oyelaran",
    name: "Marcus Oyelaran",
    role: "Toolmaker",
    org: "Oyelaran Edge",
    place: "Sheffield",
    initials: "MO",
    bio: [
      "Marcus makes and restores edge tools, and has an unfashionable interest in the ones that were designed to be resharpened for a century.",
      "He teaches sharpening to anyone who asks, on the grounds that a blunt tool is the most common cause of a ruined piece of work.",
    ],
  },
  {
    id: "s07",
    slug: "ines-caballero",
    name: "Inés Caballero",
    role: "Head of collections",
    org: "Northfield Industrial Museum",
    place: "Detroit",
    initials: "IC",
    bio: [
      "Inés looks after about 90,000 objects with a team of four, which she says is a resourcing problem disguised as a cataloguing problem.",
      "She is interested in the point at which an uncatalogued collection stops being a collection at all.",
    ],
  },
  {
    id: "s08",
    slug: "ben-ostrowski",
    name: "Ben Ostrowski",
    role: "Site reliability lead",
    org: "Marrow Health",
    place: "Boston",
    initials: "BO",
    bio: [
      "Ben has carried a pager for eleven years across three industries and has come to believe that most on-call rotas are a way of not making a decision.",
      "He writes about the design of escalation policies, which is a smaller field than it should be.",
    ],
  },
  {
    id: "s09",
    slug: "yuki-tanabe",
    name: "Yuki Tanabe",
    role: "Archivist",
    org: "Ferrous Archive Project",
    place: "Portland",
    initials: "YT",
    bio: [
      "Yuki works on industrial records that arrive in filing cabinets and leave as something a researcher can actually use.",
      "She has a particular interest in formats that were readable for thirty years and then abruptly were not.",
    ],
  },
  {
    id: "s10",
    slug: "gerald-nkemelu",
    name: "Gerald Nkemelu",
    role: "Track maintenance supervisor",
    org: "Riverline Rail",
    place: "St. Louis",
    initials: "GN",
    bio: [
      "Gerald has run night gangs on regional track for nineteen years and has trained about a third of the current supervisors on his division.",
      "He speaks rarely and is worth listening to closely when he does.",
    ],
  },
  {
    id: "s11",
    slug: "aoife-brennan",
    name: "Aoife Brennan",
    role: "Care researcher",
    org: "University of the Northlands",
    place: "Dundee",
    initials: "AB",
    bio: [
      "Aoife studies maintenance as a form of care work, and the political consequences of it being counted as neither.",
      "Her current project follows six people whose jobs consist entirely of things that are invisible when done correctly.",
    ],
  },
  {
    id: "s12",
    slug: "harun-celik",
    name: "Harun Çelik",
    role: "Standards editor",
    org: "ISO/TC 315 secretariat",
    place: "Ankara",
    initials: "HÇ",
    bio: [
      "Harun edits standards for a living, which he cheerfully admits sounds like a punishment and is in fact a study of how consensus is actually reached.",
      "He has watched one clause take four years, and thinks that was about right.",
    ],
  },
  {
    id: "s13",
    slug: "nadia-lindqvist",
    name: "Nadia Lindqvist",
    role: "Building surveyor",
    org: "Lindqvist Survey",
    place: "Gothenburg",
    initials: "NL",
    bio: [
      "Nadia is called in when a building has started doing something nobody expected, which she says is nearly always water and occasionally politics.",
      "She teaches a short course on reading a structure before opening it up.",
    ],
  },
  {
    id: "s14",
    slug: "curtis-hallam",
    name: "Curtis Hallam",
    role: "Sanitation operations",
    org: "City of Ravensworth",
    place: "Ravensworth",
    initials: "CH",
    bio: [
      "Curtis runs the crews responsible for about 900 miles of sewer, and is the person actually woken up when it goes wrong.",
      "He has a low tolerance for asset-management software written by people who have never been in a manhole.",
    ],
  },
  {
    id: "s15",
    slug: "sara-mbeki",
    name: "Sara Mbeki",
    role: "Product director",
    org: "Civic Software Collective",
    place: "Atlanta",
    initials: "SM",
    bio: [
      "Sara builds software for small municipalities, and spends most of her time on the question of what happens to it when the grant that paid for it ends.",
      "She has inherited nine abandoned systems and buried four.",
    ],
  },
  {
    id: "s16",
    slug: "olek-vasilenko",
    name: "Olek Vasilenko",
    role: "Bicycle mechanic",
    org: "Third Gear Co-op",
    place: "Milwaukee",
    initials: "OV",
    bio: [
      "Olek runs a co-operative workshop that repairs about 3,000 bicycles a year, most of them for people who could not otherwise get to work.",
      "He keeps a wall of parts that manufacturers no longer make and can tell you the year each one stopped.",
    ],
  },
  {
    id: "s17",
    slug: "margaret-oduya",
    name: "Margaret Oduya",
    role: "Public finance analyst",
    org: "Office of the State Auditor",
    place: "Harrisburg",
    initials: "MO",
    bio: [
      "Margaret audits capital budgets, and has spent several years arguing that deferred maintenance belongs on a balance sheet.",
      "She has a memorable line about compound interest that this conference invited her specifically to deliver.",
    ],
  },
  {
    id: "s18",
    slug: "felix-thornbury",
    name: "Felix Thornbury",
    role: "Canal warden",
    org: "Lowland Waterways Trust",
    place: "Stoke",
    initials: "FT",
    bio: [
      "Felix looks after eleven miles of a canal built in 1798, using a mixture of Victorian engineering drawings and a great deal of accumulated local knowledge.",
      "He keeps field notes by hand and has forty years of them.",
    ],
  },
  {
    id: "s19",
    slug: "lena-frisch",
    name: "Lena Frisch",
    role: "Documentation lead",
    org: "Halcyon Systems",
    place: "Berlin",
    initials: "LF",
    bio: [
      "Lena is responsible for documentation across a platform with about 200 engineers writing into it, and treats rot as a measurable quantity.",
      "She publishes an internal decay report that is genuinely read.",
    ],
  },
  {
    id: "s20",
    slug: "tobias-nwachukwu",
    name: "Tobias Nwachukwu",
    role: "Insurance underwriter",
    org: "Meridian Mutual",
    place: "Hartford",
    initials: "TN",
    bio: [
      "Tobias prices risk on industrial and municipal assets, which makes him one of the few people whose job depends on maintenance actually happening.",
      "He is interested in insurance as an accidental regulator.",
    ],
  },
  {
    id: "s21",
    slug: "clara-benitez",
    name: "Clara Benítez",
    role: "Repair café organiser",
    org: "Fix It Fridays",
    place: "San Antonio",
    initials: "CB",
    bio: [
      "Clara has run a monthly repair café for six years and keeps records of everything brought in, which turns out to be a small research dataset.",
      "About a third of what arrives is fixed with a part that costs under two dollars.",
    ],
  },
  {
    id: "s22",
    slug: "raymond-pike",
    name: "Raymond Pike",
    role: "Facilities manager",
    org: "Abbotsford Baths",
    place: "Manchester",
    initials: "RP",
    bio: [
      "Raymond has run the same municipal swimming baths since 1998 and has kept every maintenance record since he arrived.",
      "The building is 1904 and has outlived six plans to close it.",
    ],
  },
  {
    id: "s23",
    slug: "esme-lindgren",
    name: "Esme Lindgren",
    role: "Timber conservator",
    org: "Independent",
    place: "Bergen",
    initials: "EL",
    bio: [
      "Esme works on historic joinery and spends a surprising amount of her time persuading clients not to replace things.",
      "Her rule of thumb is that the second repair is the one that does the damage.",
    ],
  },
  {
    id: "s24",
    slug: "kwame-asante",
    name: "Kwame Asante",
    role: "Platform engineer",
    org: "Northbound",
    place: "Toronto",
    initials: "KA",
    bio: [
      "Kwame has run three large deprecations and describes the first as a cautionary tale he tells at his own expense.",
      "He argues that a deprecation is a promise about the future rather than an announcement about the present.",
    ],
  },
  {
    id: "s25",
    slug: "juliet-marchetti",
    name: "Juliet Marchetti",
    role: "Programme director",
    org: "Small Museums Network",
    place: "Providence",
    initials: "JM",
    bio: [
      "Juliet supports about 140 museums with fewer than five staff each, which is most of the museums in the country and almost none of the funding.",
      "She is very direct about what volunteers can and cannot be asked to hold up.",
    ],
  },
  {
    id: "s26",
    slug: "arne-dahl",
    name: "Arne Dahl",
    role: "Inspection consultant",
    org: "Dahl Assurance",
    place: "Oslo",
    initials: "AD",
    bio: [
      "Arne designs inspection regimes and then, more usefully, goes back years later to find out whether they inspected anything.",
      "The answer is frequently no, for reasons he finds more interesting than depressing.",
    ],
  },
  {
    id: "s27",
    slug: "wendy-okonkwo",
    name: "Wendy Okonkwo",
    role: "Highways engineer",
    org: "County of Marrowfield",
    place: "Marrowfield",
    initials: "WO",
    bio: [
      "Wendy is responsible for roads that four different bodies believe somebody else owns, which she has mapped in some detail.",
      "The map is the talk.",
    ],
  },
  {
    id: "s28",
    slug: "samir-haddad",
    name: "Samir Haddad",
    role: "Right to repair advocate",
    org: "Openparts",
    place: "Montreal",
    initials: "SH",
    bio: [
      "Samir has spent three years on legislative work around parts availability and repair documentation.",
      "He is careful to distinguish what the law now requires from what has actually changed in a workshop.",
    ],
  },
  {
    id: "s29",
    slug: "greta-solberg",
    name: "Greta Solberg",
    role: "Roofer",
    org: "Solberg & Daughters",
    place: "Trondheim",
    initials: "GS",
    bio: [
      "Greta is the fourth generation of her family to work on the same category of roof, and in several cases on the same roofs.",
      "She has the maintenance ledgers to prove it, going back to 1871.",
    ],
  },
  {
    id: "s30",
    slug: "victor-almazan",
    name: "Victor Almazán",
    role: "Grants officer",
    org: "Hearthstone Foundation",
    place: "Denver",
    initials: "VA",
    bio: [
      "Victor gives away about $12m a year and is unusually candid about the mismatch between a three-year grant cycle and a forty-year roof.",
      "He is trying to change it from the inside, slowly.",
    ],
  },
];
