import type { Customer } from "./types";

/**
 * The people writing in.
 *
 * `plan` is the load-bearing field: it is the only thing that decides
 * how fast we have promised to answer, so it is what turns one of
 * these conversations red and leaves the rest alone.
 *
 * Rosa has never written in. A contacts list where every row has
 * history never shows its own empty state — CONVENTIONS §7b — and a
 * customer who has bought something and never needed help is the most
 * ordinary customer there is.
 */
export const customers: Customer[] = [
  {
    id: "cu-marta",
    name: "Marta Vogel",
    company: "Vogel Studio",
    email: "marta@vogelstudio.example",
    plan: "Pro",
    location: "Leipzig, Germany",
    since: "2024-06-02",
    initials: "MV",
    note: "Runs a recording studio. Uses four Harrow 2s as a monitoring set, so a pairing fault affects all of them at once.",
  },
  {
    id: "cu-colin",
    name: "Colin Reyes",
    company: "—",
    email: "c.reyes@fastmail.example",
    plan: "Standard",
    location: "Cardiff, Wales",
    since: "2025-11-18",
    initials: "CR",
    note: null,
  },
  {
    id: "cu-priyanka",
    name: "Priyanka Shah",
    company: "Ardent Fitness",
    email: "priyanka@ardentfitness.example",
    plan: "Pro",
    location: "Manchester, England",
    since: "2025-02-27",
    initials: "PS",
    note: "Twelve units across three studios. Any battery fault is likely to be reported as a batch.",
  },
  {
    id: "cu-dan",
    name: "Dan Whitlock",
    company: "—",
    email: "dwhitlock@mailbox.example",
    plan: "Free",
    location: "Bristol, England",
    since: "2026-01-09",
    initials: "DW",
    note: null,
  },
  {
    id: "cu-fiona",
    name: "Fiona Kerr",
    company: "—",
    email: "fiona.kerr@post.example",
    plan: "Standard",
    location: "Glasgow, Scotland",
    since: "2025-08-14",
    initials: "FK",
    note: "Second return this year, both genuine faults. Ruth has agreed to cover return postage without asking again.",
  },
  {
    id: "cu-sam",
    name: "Sam Okonjo",
    company: "Okonjo Sound",
    email: "sam@okonjosound.example",
    plan: "Pro",
    location: "Lagos, Nigeria",
    since: "2024-03-21",
    initials: "SO",
    note: "Reports faults precisely and tests what we ask him to. Worth reading his messages in full.",
  },
  {
    id: "cu-ilse",
    name: "Ilse Brandt",
    company: "Brandt & Lomax",
    email: "i.brandt@brandtlomax.example",
    plan: "Standard",
    location: "Rotterdam, Netherlands",
    since: "2025-05-30",
    initials: "IB",
    note: "Buys through the company. Invoices go to accounts, not to her.",
  },
  {
    id: "cu-greg",
    name: "Greg Alonso",
    company: "—",
    email: "greg.alonso@webmail.example",
    plan: "Free",
    location: "Seville, Spain",
    since: "2026-02-02",
    initials: "GA",
    note: null,
  },
  {
    id: "cu-neve",
    name: "Neve Sutherland",
    company: "—",
    email: "neve.s@inbox.example",
    plan: "Standard",
    location: "Inverness, Scotland",
    since: "2026-02-19",
    initials: "NS",
    note: null,
  },
  {
    id: "cu-marcus",
    name: "Marcus Bell",
    company: "—",
    email: "mbell@mailbox.example",
    plan: "Free",
    location: "Leeds, England",
    since: "2025-12-01",
    initials: "MB",
    note: null,
  },
  {
    id: "cu-hannah",
    name: "Hannah Lidell",
    company: "Lidell Hospitality",
    email: "hannah@lidellhospitality.example",
    plan: "Standard",
    location: "Dublin, Ireland",
    since: "2025-09-11",
    initials: "HL",
    note: "Fits out hotel rooms. Trade enquiries from her are real.",
  },
  {
    id: "cu-otto",
    name: "Otto Reinhardt",
    company: "—",
    email: "otto.reinhardt@post.example",
    plan: "Pro",
    location: "Vienna, Austria",
    since: "2024-11-05",
    initials: "OR",
    note: "Sends a lot of product ideas. Several of them have shipped.",
  },
  {
    id: "cu-aleksy",
    name: "Aleksy Nowak",
    company: "Nowak Field Recording",
    email: "aleksy@nowakfield.example",
    plan: "Pro",
    location: "Kraków, Poland",
    since: "2024-09-16",
    initials: "AN",
    note: "Works outdoors in the cold, which is relevant to nearly every battery question he asks.",
  },
  {
    id: "cu-rosa",
    name: "Rosa Iglesias",
    company: "—",
    email: "rosa.iglesias@correo.example",
    plan: "Standard",
    location: "Valencia, Spain",
    since: "2025-07-08",
    initials: "RI",
    note: null,
  },
];
