import type { Accession } from "./types";

/**
 * Fifty-nine accessions, and every window in here is the real season a
 * mild Atlantic garden gets — which is the whole reason the site's
 * argument works.
 *
 * A garden on this coast is warmed by the sea and wet all year, so it
 * front-loads violently: magnolias and the big rhododendrons in March,
 * everything Chilean in late May, and then a long green nothing through
 * high summer that continental gardens do not have. Autumn colour is
 * genuinely poorer here than inland because the first frost arrives too
 * late and too gently. None of that is invented; only the garden is.
 *
 * TUNED PER §7b so every state the design can show is reached, and each
 * of these is asserted by `scripts/check-season.mjs` rather than left as
 * an intention:
 *
 *   · one week is clearly the best (11) and one clearly the worst (38),
 *     and the worst is in SEPTEMBER, which is the model telling us
 *     something rather than us telling it something — the first draft
 *     of the copy confidently said November, and the arithmetic did not
 *     agree. The prose was changed, not the plants.
 *   · a run of weeks is genuinely thin, so "not much on" is a real state
 *   · one plant is above the bar for two weeks and takes seven years to
 *     get there (the cardiocrinum)
 *   · one is above it for twenty-plus (the paperbark maple's bark)
 *   · one area has nothing for over half the year (the Shore Walk)
 *   · one area is the only thing carrying deep winter (the Glasshouse)
 *   · two of the most photographed things here can never be seen on the
 *     same day, and they miss each other by three weeks
 *   · one plant never gets above the bar at all, in any week, and it is
 *     the reason the rest of the garden is alive
 */
export const collection: Accession[] = [
  // ── The Hollow ────────────────────────────────────────────────────
  {
    id: "1931-044",
    slug: "magnolia-campbellii",
    name: "Magnolia campbellii",
    common: "Campbell's magnolia",
    family: "Magnoliaceae",
    area: "hollow",
    kind: "flower",
    from: 10,
    peak: 11,
    to: 12,
    strength: 10,
    colour: "oklch(0.78 0.110 0)",
    origin: "Sikkim. Grown from seed sent to Marchbank in 1929.",
    planted: 1931,
    note: "Twenty-six years from seed to first flower, and it has not missed a year since 1957. It opens on bare wood, forty feet up, and it is the only thing in this garden you can see from the far side of the loch. An east wind at the wrong moment browns the whole tree in a night — that has happened four times in ninety years, most recently in 2019.",
    photo: "magnolia",
  },
  {
    id: "1934-011",
    slug: "magnolia-lanarth",
    name: "Magnolia campbellii subsp. mollicomata 'Lanarth'",
    common: null,
    family: "Magnoliaceae",
    area: "hollow",
    kind: "flower",
    from: 10,
    peak: 12,
    to: 15,
    strength: 9,
    colour: "oklch(0.55 0.160 340)",
    origin: "Garden origin. Cutting material, 1934.",
    planted: 1934,
    note: "A far harder colour than the species — closer to beetroot than pink, and it looks wrong in photographs and right in person. Flowers a week later than its neighbour, which is the only reason the Hollow has two good weeks in March instead of one.",
    photo: null,
  },
  {
    id: "1881-002",
    slug: "rhododendron-arboreum",
    name: "Rhododendron arboreum",
    common: null,
    family: "Ericaceae",
    area: "hollow",
    kind: "flower",
    from: 8,
    peak: 11,
    to: 14,
    strength: 9,
    colour: "oklch(0.50 0.190 25)",
    origin: "Nepal, via a Cornish nursery. One of the original 1881 planting.",
    planted: 1881,
    note: "The second plant that ever went in the ground here and the oldest thing in the collection. Blood red, and high enough now that most of the flower is above head height where nobody looks.",
    photo: null,
  },
  {
    id: "1913-058",
    slug: "rhododendron-falconeri",
    name: "Rhododendron falconeri",
    common: null,
    family: "Ericaceae",
    area: "hollow",
    kind: "flower",
    from: 12,
    peak: 14,
    to: 17,
    strength: 9,
    colour: "oklch(0.91 0.050 95)",
    origin: "Bhutan. Ellis, 1913.",
    planted: 1913,
    note: "Cream trusses the size of a football, but the leaf is the real thing — a foot long, dark above and rust-felted underneath, and it holds that felt for three years before it wears off.",
    photo: null,
  },
  {
    id: "1926-107",
    slug: "rhododendron-sinogrande",
    name: "Rhododendron sinogrande",
    common: null,
    family: "Ericaceae",
    area: "hollow",
    kind: "leaf",
    from: 13,
    peak: 15,
    to: 19,
    strength: 8,
    colour: "oklch(0.45 0.080 145)",
    origin: "Yunnan. Rowat, 1926.",
    planted: 1926,
    note: "The largest leaf of any rhododendron in cultivation and the reason people photograph this plant with a hand held up beside it. It flowers as well, creamy and enormous, but the flowers are almost beside the point and it does not bother every year.",
    photo: null,
  },
  {
    id: "1968-021",
    slug: "rhododendron-polar-bear",
    name: "Rhododendron 'Polar Bear'",
    common: null,
    family: "Ericaceae",
    area: "hollow",
    kind: "scent",
    from: 27,
    peak: 29,
    to: 31,
    strength: 6,
    colour: "oklch(0.96 0.012 100)",
    origin: "Garden origin, raised in Sussex before 1926.",
    planted: 1968,
    note: "A rhododendron that flowers in the third week of July, which sounds like a misprint and is not. Enormous white lilies of things, scented like nothing else in the garden, and single-handedly responsible for the Hollow being worth walking into in high summer.",
    photo: null,
  },
  {
    id: "1955-090",
    slug: "corylopsis-pauciflora",
    name: "Corylopsis pauciflora",
    common: "Buttercup winter hazel",
    family: "Hamamelidaceae",
    area: "hollow",
    kind: "flower",
    from: 11,
    peak: 13,
    to: 15,
    strength: 5,
    colour: "oklch(0.90 0.090 100)",
    origin: "Taiwan and Japan. Nursery stock.",
    planted: 1955,
    note: "Pale primrose bells on bare twigs, hung the whole length of the branch. It is a quiet plant standing next to very loud ones and it wins about one visitor in twenty.",
    photo: null,
  },
  {
    id: "1972-140",
    slug: "erythronium-pagoda",
    name: "Erythronium 'Pagoda'",
    common: "Dog's-tooth violet",
    family: "Liliaceae",
    area: "hollow",
    kind: "flower",
    from: 13,
    peak: 15,
    to: 17,
    strength: 5,
    colour: "oklch(0.85 0.140 95)",
    origin: "Garden origin.",
    planted: 1972,
    note: "Planted as two hundred bulbs under the falconeri. There are now something over nine thousand and we have stopped counting; they are moving downhill about a metre a year on their own.",
    photo: null,
  },
  {
    id: "1979-033",
    slug: "trillium-chloropetalum",
    name: "Trillium chloropetalum",
    common: "Giant wakerobin",
    family: "Melanthiaceae",
    area: "hollow",
    kind: "flower",
    from: 14,
    peak: 16,
    to: 19,
    strength: 5,
    colour: "oklch(0.38 0.110 15)",
    origin: "California. Seed exchange, 1977.",
    planted: 1979,
    note: "Seven years from seed to a flowering plant, which is why nobody sells them cheaply and why we ask you to stay on the path.",
    photo: null,
  },
  {
    id: "1962-004",
    slug: "galanthus-atkinsii",
    name: "Galanthus 'Atkinsii'",
    common: "Snowdrop",
    family: "Amaryllidaceae",
    area: "hollow",
    kind: "flower",
    from: 3,
    peak: 6,
    to: 9,
    strength: 6,
    colour: "oklch(0.97 0.008 110)",
    origin: "Garden origin, pre-1890.",
    planted: 1962,
    note: "Taller and earlier than the common one, and it increases fast in leaf mould. Four hundred metres of the Hollow path is edged with it and the whole lot came from one clump lifted out of a Perthshire churchyard.",
    photo: "snowdrops",
  },
  {
    id: "1988-050",
    slug: "helleborus-hybridus",
    name: "Helleborus × hybridus",
    common: "Lenten rose",
    family: "Ranunculaceae",
    area: "hollow",
    kind: "flower",
    from: 3,
    peak: 7,
    to: 13,
    strength: 6,
    colour: "oklch(0.42 0.100 350)",
    origin: "Garden seedlings, open pollinated.",
    planted: 1988,
    note: "Every one of these is a seedling and no two are the same colour. They face the ground, so the only way to see one properly is to lie down, and we would ask you not to do that on the path in February.",
    photo: null,
  },
  {
    id: "1991-018",
    slug: "cyclamen-coum",
    name: "Cyclamen coum",
    common: null,
    family: "Primulaceae",
    area: "hollow",
    kind: "flower",
    from: 2,
    peak: 5,
    to: 9,
    strength: 4,
    colour: "oklch(0.66 0.160 350)",
    origin: "Northern Turkey. Seed, 1989.",
    planted: 1991,
    note: "Four centimetres tall and shocking magenta against dead oak leaves. Ants move the seed, which is why it turns up ten metres from where anybody planted it.",
    photo: null,
  },
  {
    id: "1965-112",
    slug: "hydrangea-aspera",
    name: "Hydrangea aspera Villosa Group",
    common: null,
    family: "Hydrangeaceae",
    area: "hollow",
    kind: "flower",
    from: 31,
    peak: 34,
    to: 38,
    strength: 6,
    colour: "oklch(0.62 0.090 300)",
    origin: "Western China. Nursery stock.",
    planted: 1965,
    note: "Velvet leaves and a flat lace-cap in lilac and dull mauve, and it is one of about four things holding this garden together in late August. Nothing like the mophead hydrangeas in the village.",
    photo: "hydrangea",
  },
  {
    id: "1958-076",
    slug: "acer-osakazuki",
    name: "Acer palmatum 'Osakazuki'",
    common: null,
    family: "Sapindaceae",
    area: "hollow",
    kind: "leaf",
    from: 40,
    peak: 43,
    to: 46,
    strength: 7,
    colour: "oklch(0.52 0.200 30)",
    origin: "Japan, via nursery stock.",
    planted: 1958,
    note: "The most reliable scarlet in the garden and the only autumn plant here that does the same thing every year regardless of the weather. Everything else on this hillside depends on a cold snap we usually do not get.",
    photo: "acer",
  },
  {
    id: "1970-062",
    slug: "enkianthus-campanulatus",
    name: "Enkianthus campanulatus",
    common: null,
    family: "Ericaceae",
    area: "hollow",
    kind: "leaf",
    from: 41,
    peak: 43,
    to: 46,
    strength: 5,
    colour: "oklch(0.60 0.160 45)",
    origin: "Japan. Nursery stock.",
    planted: 1970,
    note: "Flowers in May, and nobody comes for them. It earns its place in the third week of October, when it goes through orange to a hard scarlet from the outside of the bush inwards.",
    photo: null,
  },

  // ── Burnside Walk ─────────────────────────────────────────────────
  {
    id: "1953-006",
    slug: "meconopsis-slieve-donard",
    name: "Meconopsis 'Slieve Donard'",
    common: "Himalayan blue poppy",
    family: "Papaveraceae",
    area: "burnside",
    kind: "flower",
    from: 20,
    peak: 23,
    to: 27,
    strength: 9,
    colour: "oklch(0.55 0.170 258)",
    origin: "Garden origin, Northern Ireland, 1930s.",
    planted: 1953,
    note: "The colour photographs badly on every camera ever made, including yours — it comes out purple. In life it is a genuine sky blue and it is the only week of the year this garden is not fundamentally red, cream and green. It needs cool, wet and shade, which is the one thing Argyll can guarantee.",
    photo: null,
  },
  {
    id: "1950-029",
    slug: "primula-pulverulenta",
    name: "Primula pulverulenta",
    common: "Candelabra primula",
    family: "Primulaceae",
    area: "burnside",
    kind: "flower",
    from: 18,
    peak: 22,
    to: 27,
    strength: 6,
    colour: "oklch(0.52 0.190 355)",
    origin: "Sichuan. Original planting lost; these are self-sown.",
    planted: 1950,
    note: "Nobody has planted one of these since about 1961. They have seeded the entire length of the burn and hybridised with everything else in the genus, so the colour now runs from brick to magenta to a washed-out apricot that we quite like and did not choose.",
    photo: null,
  },
  {
    id: "1922-039",
    slug: "crinodendron-hookerianum",
    name: "Crinodendron hookerianum",
    common: "Lantern tree",
    family: "Elaeocarpaceae",
    area: "burnside",
    kind: "flower",
    from: 19,
    peak: 21,
    to: 25,
    strength: 8,
    colour: "oklch(0.52 0.180 22)",
    origin: "Chile. Ellis, 1922.",
    planted: 1922,
    note: "Crimson lanterns hung along the underside of every branch on long stalks, so you have to be below it to see anything at all. Wants exactly what the burn provides — acid, damp, and never a dry root.",
    photo: null,
  },
  {
    id: "2018-003",
    slug: "cardiocrinum-giganteum",
    name: "Cardiocrinum giganteum",
    common: "Giant Himalayan lily",
    family: "Liliaceae",
    area: "burnside",
    kind: "flower",
    from: 29,
    peak: 29,
    to: 30,
    strength: 9,
    colour: "oklch(0.93 0.040 120)",
    origin: "Himalaya. Seed, 2011.",
    planted: 2018,
    note: "Seven years underground building a bulb, then three metres of stem in ten weeks, twenty white trumpets, a smell you can find from forty feet away in the dark — and then the whole plant dies. It leaves offsets, which start their own seven years. This is the single narrowest window in the collection and the only thing here we will telephone people about.",
    photo: null,
  },
  {
    id: "1908-014",
    slug: "dicksonia-antarctica",
    name: "Dicksonia antarctica",
    common: "Soft tree fern",
    family: "Dicksoniaceae",
    area: "burnside",
    kind: "form",
    from: 18,
    peak: 27,
    to: 42,
    strength: 5,
    colour: "oklch(0.55 0.100 145)",
    origin: "Tasmania. Trunks imported 1908.",
    planted: 1908,
    note: "Eleven of them along the wettest hundred metres, and the tallest has put on about two and a half metres of trunk in a hundred and seventeen years. They are not hardy anywhere in Britain that the sea does not reach.",
    photo: "ferns",
  },
  {
    id: "1949-071",
    slug: "gunnera-manicata",
    name: "Gunnera manicata",
    common: null,
    family: "Gunneraceae",
    area: "burnside",
    kind: "form",
    from: 22,
    peak: 30,
    to: 40,
    strength: 5,
    colour: "oklch(0.50 0.090 140)",
    origin: "Brazil. Nursery stock.",
    planted: 1949,
    note: "Leaves you can stand under in a shower and stay dry. We fold the dead leaves over the crowns in November to keep the frost out, which is the single ugliest thing in the garden for four months of the year.",
    photo: "gunnera",
  },
  {
    id: "1966-023",
    slug: "narcissus-cyclamineus",
    name: "Narcissus cyclamineus",
    common: null,
    family: "Amaryllidaceae",
    area: "burnside",
    kind: "flower",
    from: 8,
    peak: 11,
    to: 14,
    strength: 5,
    colour: "oklch(0.83 0.160 92)",
    origin: "Portugal. Seed, 1964.",
    planted: 1966,
    note: "The tiny one with its petals swept straight back, as though it is facing into wind. Naturalised in the wet grass at the bottom, which is the only place in Britain it does that willingly.",
    photo: null,
  },
  {
    id: "1954-088",
    slug: "lysichiton-americanus",
    name: "Lysichiton americanus",
    common: "American skunk cabbage",
    family: "Araceae",
    area: "burnside",
    kind: "flower",
    from: 11,
    peak: 13,
    to: 16,
    strength: 4,
    colour: "oklch(0.86 0.150 100)",
    origin: "Pacific north-west America. Nursery stock, 1954.",
    planted: 1954,
    note: "A metre of acid-yellow hood standing in the water in March, and it smells exactly as advertised. It has been illegal to sell or plant this in Britain since 2016 because of what it does to a river system. Ours predates that by sixty years, so we keep it, cut every seed head off by hand, and have never found it below the bridge.",
    photo: null,
  },

  // ── The South Terrace ─────────────────────────────────────────────
  {
    id: "1919-051",
    slug: "embothrium-coccineum",
    name: "Embothrium coccineum",
    common: "Chilean fire bush",
    family: "Proteaceae",
    area: "terrace",
    kind: "flower",
    from: 20,
    peak: 22,
    to: 25,
    strength: 10,
    colour: "oklch(0.58 0.220 32)",
    origin: "Chile, 41° S. Ellis, 1919.",
    planted: 1919,
    note: "The most saturated thing in the garden by a distance — an orange-scarlet with no pink in it that reads as artificial until you are standing under it. Twelve metres now. It suckers, so there are nine of them where one was planted, and in the last week of May the whole terrace end of the garden is on fire.",
    photo: null,
  },
  {
    id: "1936-025",
    slug: "eucryphia-nymansay",
    name: "Eucryphia × nymansensis 'Nymansay'",
    common: null,
    family: "Cunoniaceae",
    area: "terrace",
    kind: "flower",
    from: 32,
    peak: 34,
    to: 38,
    strength: 8,
    colour: "oklch(0.97 0.010 100)",
    origin: "Garden origin, Sussex, 1914.",
    planted: 1936,
    note: "A column of white the height of a house, in the last fortnight of August, when there is nothing else. Every bee in Argyll is in it and you can hear the tree from the path. If one plant justifies coming here in the summer holidays it is this one.",
    photo: null,
  },
  {
    id: "1948-030",
    slug: "camellia-donation",
    name: "Camellia × williamsii 'Donation'",
    common: null,
    family: "Theaceae",
    area: "terrace",
    kind: "flower",
    from: 6,
    peak: 10,
    to: 16,
    strength: 8,
    colour: "oklch(0.75 0.110 5)",
    origin: "Garden origin, 1941.",
    planted: 1948,
    note: "Drops its dead flowers cleanly instead of hanging on to them brown, which is the entire reason this cultivar exists and why it is planted in front of the house rather than behind it.",
    photo: "camellia",
  },
  {
    id: "1994-002",
    slug: "daphne-bholua",
    name: "Daphne bholua 'Jacqueline Postill'",
    common: null,
    family: "Thymelaeaceae",
    area: "terrace",
    kind: "scent",
    from: 1,
    peak: 5,
    to: 10,
    strength: 8,
    colour: "oklch(0.85 0.050 350)",
    origin: "Garden origin, from Nepalese material.",
    planted: 1994,
    note: "You will smell it from the car park in the first week of February, thirty metres away, in the rain. There is very little to see — small waxy pink-white clusters — and it is on this list at strength eight anyway, because a smell in February is worth more than a flower in June.",
    photo: null,
  },
  {
    id: "1986-044",
    slug: "sarcococca-confusa",
    name: "Sarcococca confusa",
    common: "Christmas box",
    family: "Buxaceae",
    area: "terrace",
    kind: "scent",
    from: 49,
    peak: 3,
    to: 8,
    strength: 6,
    colour: "oklch(0.94 0.020 90)",
    origin: "Western China. Nursery stock.",
    planted: 1986,
    note: "Flowers you would walk past without noticing — white threads, a few millimetres — attached to a smell like vanilla and something sharper, in January. Planted either side of the ticket hut deliberately.",
    photo: null,
  },
  {
    id: "1976-017",
    slug: "pieris-forest-flame",
    name: "Pieris 'Forest Flame'",
    common: null,
    family: "Ericaceae",
    area: "terrace",
    kind: "leaf",
    from: 13,
    peak: 16,
    to: 20,
    strength: 6,
    colour: "oklch(0.58 0.190 30)",
    origin: "Garden origin, Surrey, 1946.",
    planted: 1976,
    note: "The new growth comes out scarlet and fades through pink and cream to green over about five weeks, so the bush is four colours at once in the middle of April. Not a flower on this list; a leaf pretending to be one.",
    photo: null,
  },
  {
    id: "1963-093",
    slug: "clerodendrum-trichotomum",
    name: "Clerodendrum trichotomum var. fargesii",
    common: null,
    family: "Lamiaceae",
    area: "terrace",
    kind: "fruit",
    from: 36,
    peak: 39,
    to: 43,
    strength: 5,
    colour: "oklch(0.62 0.110 200)",
    origin: "China. Nursery stock.",
    planted: 1963,
    note: "A turquoise berry sitting in a scarlet star — a colour combination that has no business existing outside a paint chart. Crush a leaf and it smells strongly of peanut butter, which is not a joke and which most people refuse to believe until they do it.",
    photo: null,
  },
  {
    id: "1928-066",
    slug: "azara-microphylla",
    name: "Azara microphylla",
    common: null,
    family: "Salicaceae",
    area: "terrace",
    kind: "scent",
    from: 7,
    peak: 9,
    to: 12,
    strength: 5,
    colour: "oklch(0.84 0.130 95)",
    origin: "Chile. Ellis, 1922.",
    planted: 1928,
    note: "Tiny yellow tufts hidden under the leaf, so the plant appears to be doing nothing at all. It smells overpoweringly of vanilla and warm chocolate on a still day in March and people walk in circles trying to find the source.",
    photo: null,
  },

  // ── The Arboretum ─────────────────────────────────────────────────
  {
    id: "1938-081",
    slug: "acer-griseum",
    name: "Acer griseum",
    common: "Paperbark maple",
    family: "Sapindaceae",
    area: "arboretum",
    kind: "bark",
    from: 44,
    peak: 2,
    to: 12,
    strength: 5,
    colour: "oklch(0.52 0.110 45)",
    origin: "Central China. Nursery stock, 1938.",
    planted: 1938,
    note: "Cinnamon bark that peels in translucent sheets and hangs there, and it lights up like a lamp with the low sun behind it. This is the longest useful window in the collection — about twenty weeks — because bark does not care what month it is, only where the sun is.",
    photo: "bark",
  },
  {
    id: "1949-018",
    slug: "hamamelis-pallida",
    name: "Hamamelis × intermedia 'Pallida'",
    common: "Witch hazel",
    family: "Hamamelidaceae",
    area: "arboretum",
    kind: "scent",
    from: 51,
    peak: 3,
    to: 8,
    strength: 6,
    colour: "oklch(0.86 0.152 92)",
    origin: "Garden origin. Grafted stock, 1948.",
    planted: 1949,
    note: "Strap petals the colour of weak sulphur, held directly on bare wood, in the first week of February — and a smell you find from ten metres before you find the plant. There are better witch hazels for colour and none for scent, and it is the single best argument this garden has for coming in the winter.",
    photo: "witchhazel",
  },
  {
    id: "1940-012",
    slug: "prunus-serrula",
    name: "Prunus serrula",
    common: "Tibetan cherry",
    family: "Rosaceae",
    area: "arboretum",
    kind: "bark",
    from: 42,
    peak: 50,
    to: 10,
    strength: 4,
    colour: "oklch(0.45 0.100 35)",
    origin: "Western China. Nursery stock.",
    planted: 1940,
    note: "Polished mahogany, and it stays polished because every visitor for eighty-five years has run a hand round the trunk at the same height. There is a band at four feet where the bark is glass and a band above it where it is not.",
    photo: null,
  },
  {
    id: "1961-005",
    slug: "betula-jacquemontii",
    name: "Betula utilis var. jacquemontii",
    common: "Himalayan birch",
    family: "Betulaceae",
    area: "arboretum",
    kind: "bark",
    from: 44,
    peak: 51,
    to: 11,
    strength: 4,
    colour: "oklch(0.94 0.010 95)",
    origin: "Kashmir. Seed, 1959.",
    planted: 1961,
    note: "Nine of them in a group, which is the only way to plant a white birch and the reason we washed the trunks by hand every February until 2009, when we stopped and nobody noticed.",
    photo: null,
  },
  {
    id: "1911-034",
    slug: "cercidiphyllum-japonicum",
    name: "Cercidiphyllum japonicum",
    common: "Katsura",
    family: "Cercidiphyllaceae",
    area: "arboretum",
    kind: "leaf",
    from: 39,
    peak: 42,
    to: 45,
    strength: 7,
    colour: "oklch(0.74 0.130 65)",
    origin: "Japan. Seed, 1909.",
    planted: 1911,
    note: "The leaves turn apricot and pink and then, as they fall and begin to dry, the tree smells unmistakably of burnt sugar. It lasts about four days and you can smell it from the top of the track. There is no photograph on this site that conveys the important half of this plant.",
    photo: null,
  },
  {
    id: "1929-055",
    slug: "nyssa-sylvatica",
    name: "Nyssa sylvatica",
    common: "Tupelo",
    family: "Nyssaceae",
    area: "arboretum",
    kind: "leaf",
    from: 40,
    peak: 42,
    to: 45,
    strength: 6,
    colour: "oklch(0.53 0.200 32)",
    origin: "Eastern United States. Seed, 1927.",
    planted: 1929,
    note: "The best red of any tree in Britain when it decides to do it, which here is about two years in three. It wants a cold snap to trigger properly and this coast does not reliably provide one — the reason our autumn is thinner than an arboretum three hundred miles east.",
    photo: null,
  },
  {
    id: "1957-019",
    slug: "sorbus-joseph-rock",
    name: "Sorbus 'Joseph Rock'",
    common: null,
    family: "Rosaceae",
    area: "arboretum",
    kind: "fruit",
    from: 35,
    peak: 41,
    to: 47,
    strength: 5,
    colour: "oklch(0.78 0.150 82)",
    origin: "Garden origin.",
    planted: 1957,
    note: "Amber-yellow berries that the birds leave alone until about the second week of November and then strip in a day and a half. Red-berried sorbus are gone by September; this is why we grow a yellow one.",
    photo: null,
  },
  {
    id: "1983-027",
    slug: "callicarpa-bodinieri",
    name: "Callicarpa bodinieri var. giraldii 'Profusion'",
    common: "Beautyberry",
    family: "Lamiaceae",
    area: "arboretum",
    kind: "fruit",
    from: 42,
    peak: 45,
    to: 50,
    strength: 5,
    colour: "oklch(0.50 0.150 310)",
    origin: "China. Nursery stock.",
    planted: 1983,
    note: "Metallic violet berries in tight clusters along a bare stem, a colour nothing else in the collection comes near. Birds will not touch them, which is why they are still there at Christmas.",
    photo: null,
  },
  {
    id: "1924-060",
    slug: "davidia-involucrata",
    name: "Davidia involucrata",
    common: "Handkerchief tree",
    family: "Nyssaceae",
    area: "arboretum",
    kind: "flower",
    from: 19,
    peak: 20,
    to: 23,
    strength: 7,
    colour: "oklch(0.96 0.012 100)",
    origin: "Sichuan. Seed, 1921.",
    planted: 1924,
    note: "The flower is a small brown ball; the show is two white bracts hanging under it, one long and one short, and in any wind at all the whole tree moves like laundry. Took twenty-two years to flower and has never missed since.",
    photo: null,
  },
  {
    id: "1967-041",
    slug: "cornus-kousa-chinensis",
    name: "Cornus kousa var. chinensis",
    common: null,
    family: "Cornaceae",
    area: "arboretum",
    kind: "flower",
    from: 23,
    peak: 25,
    to: 29,
    strength: 7,
    colour: "oklch(0.94 0.020 40)",
    origin: "China. Nursery stock.",
    planted: 1967,
    note: "Layered horizontal branches covered so densely in white bracts that the tree reads as a single sheet from below. Fades to dusty pink over a fortnight, which most people prefer and we do not.",
    photo: null,
  },
  {
    id: "1975-085",
    slug: "stewartia-pseudocamellia",
    name: "Stewartia pseudocamellia",
    common: null,
    family: "Theaceae",
    area: "arboretum",
    kind: "flower",
    from: 27,
    peak: 29,
    to: 32,
    strength: 4,
    colour: "oklch(0.96 0.010 95)",
    origin: "Japan and Korea. Seed, 1973.",
    planted: 1975,
    note: "White camellia flowers dropped one at a time through July, so there is always one on the grass and never many on the tree. Three seasons of interest in one plant, none of them loud, which is a fair description of the whole arboretum in summer.",
    photo: null,
  },
  {
    id: "1932-070",
    slug: "nothofagus-antarctica",
    name: "Nothofagus antarctica",
    common: "Antarctic beech",
    family: "Nothofagaceae",
    area: "arboretum",
    kind: "leaf",
    from: 40,
    peak: 43,
    to: 46,
    strength: 3,
    colour: "oklch(0.80 0.130 88)",
    origin: "Tierra del Fuego, 54° S. Ellis, 1930.",
    planted: 1932,
    note: "Tiny crimped leaves that turn hard yellow, on a tree that grows in a permanent lean whether or not there is any wind to lean away from. It comes from further south than anything else here.",
    photo: null,
  },

  // ── The Shore Walk ────────────────────────────────────────────────
  {
    id: "1971-013",
    slug: "olearia-macrodonta",
    name: "Olearia macrodonta",
    common: "New Zealand holly",
    family: "Asteraceae",
    area: "shorewalk",
    kind: "flower",
    from: 24,
    peak: 27,
    to: 30,
    strength: 5,
    colour: "oklch(0.95 0.012 100)",
    origin: "New Zealand. Nursery stock.",
    planted: 1971,
    note: "Grey holly-ish leaves and a mass of small white daisies with a smell of musk. Takes salt spray straight off the loch without marking, which about four things in this collection can do.",
    photo: null,
  },
  {
    id: "1969-047",
    slug: "escallonia-iveyi",
    name: "Escallonia 'Iveyi'",
    common: null,
    family: "Escalloniaceae",
    area: "shorewalk",
    kind: "flower",
    from: 29,
    peak: 32,
    to: 36,
    strength: 4,
    colour: "oklch(0.96 0.010 105)",
    origin: "Garden origin, Devon, 1920s.",
    planted: 1969,
    note: "Glossy dark leaves and white panicles in August, and it is the only escallonia we grow because the pink ones look wrong against this water.",
    photo: null,
  },
  {
    id: "1980-008",
    slug: "hoheria-sexstylosa",
    name: "Hoheria sexstylosa",
    common: "Ribbonwood",
    family: "Malvaceae",
    area: "shorewalk",
    kind: "flower",
    from: 30,
    peak: 32,
    to: 35,
    strength: 5,
    colour: "oklch(0.96 0.012 100)",
    origin: "New Zealand. Seed, 1978.",
    planted: 1980,
    note: "Smothered in small white flowers for about three weeks in August, at which point the tree looks like it has been snowed on. Fast, short-lived, and we plant a replacement every fifteen years on principle.",
    photo: null,
  },
  {
    id: "1965-036",
    slug: "fuchsia-magellanica",
    name: "Fuchsia magellanica",
    common: null,
    family: "Onagraceae",
    area: "shorewalk",
    kind: "flower",
    from: 27,
    peak: 34,
    to: 43,
    strength: 4,
    colour: "oklch(0.48 0.180 355)",
    origin: "Chile and Argentina. Cuttings from a roadside hedge near Oban.",
    planted: 1965,
    note: "Hedge fuchsia — the one that has naturalised along half the west coast and is treated as native by everybody who lives here. Flowers for four months without stopping, which nothing else on this walk manages.",
    photo: "fuchsia",
  },
  {
    id: "1992-055",
    slug: "hippophae-rhamnoides",
    name: "Hippophae rhamnoides",
    common: "Sea buckthorn",
    family: "Elaeagnaceae",
    area: "shorewalk",
    kind: "fruit",
    from: 37,
    peak: 42,
    to: 50,
    strength: 5,
    colour: "oklch(0.70 0.160 60)",
    origin: "British native. Planted from local stock.",
    planted: 1992,
    note: "Silver leaves all summer and then dense orange berries packed the whole length of every thorny shoot, which hold on into December. The only reason this walk is worth anything after the leaves come off.",
    photo: null,
  },
  {
    id: "1961-001",
    slug: "griselinia-littoralis",
    name: "Griselinia littoralis",
    common: null,
    family: "Griseliniaceae",
    area: "shorewalk",
    kind: "form",
    from: 1,
    peak: 26,
    to: 52,
    strength: 2,
    colour: "oklch(0.68 0.110 130)",
    origin: "New Zealand. Nursery stock, 1961.",
    planted: 1961,
    note: "Four hundred metres of hedge, three metres high, planted the year the garden was given away. It never gets above the threshold on this site in any week of the year — it has no season, no flower anybody notices and no autumn — and it is the single most important plant in the collection. Everything else here is alive because this is standing between it and the sea.",
    photo: null,
  },

  // ── The Long Glasshouse ───────────────────────────────────────────
  {
    id: "1996-011",
    slug: "acacia-dealbata",
    name: "Acacia dealbata",
    common: "Mimosa",
    family: "Fabaceae",
    area: "glasshouse",
    kind: "flower",
    from: 4,
    peak: 7,
    to: 11,
    strength: 7,
    colour: "oklch(0.85 0.150 92)",
    origin: "South-eastern Australia. Seed, 1994.",
    planted: 1996,
    note: "Fifteen feet of ferny grey leaf that goes solid yellow in February and drops pollen on everything below it. It is under glass because the one we tried outside in 1998 lived nine years and then died in a single night in March.",
    photo: "mimosa",
  },
  {
    id: "1984-029",
    slug: "nerine-sarniensis",
    name: "Nerine sarniensis",
    common: "Guernsey lily",
    family: "Amaryllidaceae",
    area: "glasshouse",
    kind: "flower",
    from: 40,
    peak: 44,
    to: 47,
    strength: 6,
    colour: "oklch(0.62 0.210 25)",
    origin: "Western Cape. Bulbs, 1984.",
    planted: 1984,
    note: "Scarlet with a metallic glitter on every petal that is actually a layer of reflective cells, and it flowers on a bare stem in November out of a pot that has been bone dry all summer. Neglect is the entire cultural requirement.",
    photo: null,
  },
  {
    id: "1974-060",
    slug: "camellia-nobilissima",
    name: "Camellia japonica 'Nobilissima'",
    common: null,
    family: "Theaceae",
    area: "glasshouse",
    kind: "flower",
    from: 47,
    peak: 51,
    to: 5,
    strength: 5,
    colour: "oklch(0.96 0.012 95)",
    origin: "Garden origin, 1834.",
    planted: 1974,
    note: "The earliest camellia there is — white, in December, under glass — and the reason there is anything at all to look at here between the last berries and the first snowdrop.",
    photo: null,
  },
  {
    id: "1990-038",
    slug: "rhododendron-fragrantissimum",
    name: "Rhododendron 'Fragrantissimum'",
    common: null,
    family: "Ericaceae",
    area: "glasshouse",
    kind: "scent",
    from: 9,
    peak: 11,
    to: 15,
    strength: 6,
    colour: "oklch(0.95 0.015 90)",
    origin: "Garden origin, 1868.",
    planted: 1990,
    note: "Too tender for the Hollow by about two degrees. White, flushed pink, and it fills sixty-two metres of glasshouse with a smell of nutmeg from one plant in a tub.",
    photo: null,
  },
  {
    id: "2004-016",
    slug: "begonia-luxurians",
    name: "Begonia luxurians",
    common: "Palm-leaf begonia",
    family: "Begoniaceae",
    area: "glasshouse",
    kind: "leaf",
    from: 24,
    peak: 32,
    to: 36,
    strength: 3,
    colour: "oklch(0.52 0.090 148)",
    origin: "Brazil. Cuttings, 2003.",
    planted: 2004,
    note: "A begonia that has decided to be a palm — a whorl of narrow leaflets on a red stem, two metres up. It is the one thing in the glasshouse worth walking past in August, which is not a strong claim and we are not making a strong one.",
    photo: null,
  },
  {
    id: "1893-003",
    slug: "hyacinthoides-non-scripta",
    name: "Hyacinthoides non-scripta",
    common: "Bluebell",
    family: "Asparagaceae",
    area: "hollow",
    kind: "flower",
    from: 16,
    peak: 18,
    to: 21,
    strength: 8,
    colour: "oklch(0.52 0.150 285)",
    origin: "Native. Already here in 1878.",
    planted: 1893,
    note: "Nobody planted these and the first record of anyone counting them is 1893. Four hectares of the oak wood go violet for about ten days at the start of May, and the smell on a still warm evening is the single most underrated thing in this garden. They are the true native, not the Spanish one — we pull that out wherever it appears, which is a losing battle we intend to keep losing slowly.",
    photo: "bluebells",
  },
  {
    id: "1927-016",
    slug: "rhododendron-loderi-king-george",
    name: "Rhododendron 'Loderi King George'",
    common: null,
    family: "Ericaceae",
    area: "hollow",
    kind: "scent",
    from: 16,
    peak: 18,
    to: 21,
    strength: 8,
    colour: "oklch(0.93 0.030 20)",
    origin: "Garden origin, Sussex, 1901.",
    planted: 1927,
    note: "Pink in bud, opening to a white the size of a dinner plate, and scented like a lily from twenty metres downwind. Nine metres across now. The bluebells come out underneath it in the same fortnight, which was not planned by anybody and is the best accident in the garden.",
    photo: null,
  },
  {
    id: "1930-052",
    slug: "rhododendron-augustinii",
    name: "Rhododendron augustinii",
    common: null,
    family: "Ericaceae",
    area: "hollow",
    kind: "flower",
    from: 15,
    peak: 17,
    to: 20,
    strength: 7,
    colour: "oklch(0.58 0.140 275)",
    origin: "Western China. Rowat, 1926.",
    planted: 1930,
    note: "As close to blue as the genus gets, which is to say lavender in most lights and genuinely blue for about an hour before sunset in late April. The colour depends on how cold the winter was, and we do not know why.",
    photo: null,
  },
  {
    id: "1941-023",
    slug: "magnolia-wilsonii",
    name: "Magnolia wilsonii",
    common: null,
    family: "Magnoliaceae",
    area: "hollow",
    kind: "flower",
    from: 17,
    peak: 19,
    to: 22,
    strength: 6,
    colour: "oklch(0.95 0.014 90)",
    origin: "Sichuan and Yunnan. Seed, 1939.",
    planted: 1941,
    note: "Hangs its flowers straight down, so it is planted above the path and you look up into a white cup with a ring of crimson stamens in it. The only magnolia here worth walking under rather than standing back from.",
    photo: null,
  },
  {
    id: "1935-009",
    slug: "magnolia-sprengeri-diva",
    name: "Magnolia sprengeri 'Diva'",
    common: null,
    family: "Magnoliaceae",
    area: "hollow",
    kind: "flower",
    from: 10,
    peak: 12,
    to: 14,
    strength: 8,
    colour: "oklch(0.70 0.140 355)",
    origin: "Hubei. Grafted stock, 1935.",
    planted: 1935,
    note: "Rose-pink and held upright rather than nodding, so it catches the light differently from everything else flowering that fortnight. It is the third of the four big magnolias and the one people photograph most, because it is the only one low enough to get a whole flower in the frame.",
    photo: null,
  },
];
